package main

const AMOUNT_OF_GAMES = 27

var EmptyGrig10x20 = Grid{
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
}

var pieces = []string{I, J, L, O, S, T, Z}

var g1 = [400]string{T, S, T, I, T, S, S, Z, O, T, J, Z, T, O, S, O, L, L, I, S, L, J, J, L, T, L, I, Z, L, Z, O, S, J, J, O, L, T, J, S, T, T, I, I, S, S, T, O, S, T, S, T, L, L, L, O, I, T, T, J, T, Z, J, S, T, I, S, I, L, O, T, O, Z, Z, Z, L, J, O, J, O, L, Z, L, J, I, O, J, T, Z, I, I, I, O, Z, J, T, Z, J, S, S, I, J, Z, T, L, J, Z, S, Z, Z, O, Z, O, I, Z, Z, O, L, S, L, L, J, I, T, S, Z, I, I, L, I, O, I, S, S, Z, J, I, T, Z, I, I, J, L, I, I, I, I, J, J, T, S, I, J, I, O, L, Z, L, I, S, T, J, T, Z, T, L, Z, T, L, Z, O, T, J, L, L, S, O, I, O, L, O, L, Z, J, T, O, J, L, J, I, J, Z, I, Z, Z, Z, S, I, J, O, I, T, I, J, Z, O, S, Z, S, J, I, Z, J, J, L, J, T, I, I, S, I, T, O, S, I, J, S, J, I, I, J, T, O, S, J, I, J, L, S, J, S, S, O, S, S, O, T, Z, I, S, I, T, I, I, O, O, L, L, I, O, L, I, I, T, L, O, S, I, T, S, I, Z, O, L, T, I, S, L, L, O, I, O, Z, L, L, J, S, I, L, L, Z, O, Z, S, J, L, S, O, O, J, I, T, T, J, J, J, O, J, L, Z, S, I, S, S, I, I, J, Z, I, Z, S, O, S, Z, T, L, S, L, Z, I, Z, I, I, L, I, Z, Z, I, S, S, Z, I, J, J, O, S, L, T, S, L, J, S, I, O, S, O, L, J, J, I, J, O, Z, S, O, Z, S, J, L, I, J, I, L, S, O, Z, Z, I, O, I, J, J, L, L, Z, O, Z, I, Z, I, T, Z, J, S, O, I, T, I, L, T, Z}
var g2 = [400]string{Z, I, O, J, J, S, L, L, I, I, Z, J, J, Z, O, J, T, J, T, T, T, Z, T, O, O, O, T, T, J, L, Z, I, Z, Z, T, S, Z, Z, Z, S, I, T, T, O, L, I, L, T, J, L, S, S, Z, Z, I, J, I, S, O, Z, S, O, T, L, I, Z, T, L, J, Z, Z, J, S, T, S, L, O, T, L, I, L, J, I, I, S, O, Z, S, Z, I, T, J, S, I, S, S, Z, L, Z, I, T, T, T, S, T, I, T, J, J, I, O, J, I, J, L, O, I, I, S, T, J, T, I, J, I, J, Z, O, O, O, S, I, I, L, Z, T, L, Z, L, O, L, T, O, O, L, I, S, Z, S, S, Z, L, T, T, Z, S, L, J, L, L, T, J, J, I, I, O, I, L, Z, J, L, J, L, I, I, L, I, L, J, Z, L, I, T, S, S, J, J, O, J, T, O, T, L, L, J, Z, S, S, I, I, I, S, I, T, I, O, T, Z, I, J, T, L, T, S, Z, S, I, S, O, J, L, Z, J, S, S, O, S, O, Z, S, Z, O, L, S, S, T, I, T, O, T, S, I, O, T, T, L, O, J, L, O, Z, T, L, T, T, I, L, O, Z, O, O, T, S, L, T, S, T, O, J, J, T, J, Z, L, O, O, L, O, O, I, O, Z, O, Z, L, S, S, L, O, L, Z, I, T, S, I, O, O, T, L, O, J, J, Z, I, I, T, O, O, S, T, I, T, J, L, Z, O, Z, Z, J, Z, L, J, T, T, L, Z, I, I, Z, Z, L, L, I, O, J, I, I, T, I, J, S, S, O, O, S, J, T, O, O, I, L, Z, T, J, L, I, I, L, J, J, S, I, S, L, S, S, T, I, T, S, T, J, J, Z, S, Z, S, O, Z, Z, I, Z, T, L, T, T, J, O, J, T, I, T, J, J, L, O, L, Z, O, J}
var g3 = [400]string{S, L, O, Z, S, J, O, L, Z, S, Z, Z, S, I, L, Z, Z, Z, L, Z, I, L, Z, I, O, Z, L, T, O, O, I, I, Z, O, L, T, S, O, I, I, Z, O, O, I, O, T, O, L, S, Z, L, Z, O, T, L, J, S, L, Z, T, I, J, L, Z, J, T, O, S, I, Z, O, Z, J, T, Z, J, J, S, Z, Z, T, J, T, J, Z, T, J, I, O, J, T, T, O, S, L, J, L, Z, L, S, T, S, O, O, I, T, L, S, J, Z, S, L, L, I, T, L, L, J, Z, I, T, L, T, J, L, J, I, L, T, T, J, S, T, L, O, O, J, O, S, T, I, J, T, I, S, Z, J, Z, J, J, S, I, J, L, L, Z, O, J, S, O, O, I, O, O, T, L, S, T, O, I, L, J, S, J, L, J, L, O, S, O, L, S, Z, Z, J, J, T, T, J, S, T, L, L, Z, T, O, O, S, L, O, S, S, T, S, J, O, O, L, J, J, T, I, I, J, Z, T, T, S, I, O, O, T, O, I, Z, Z, J, I, J, J, Z, J, I, T, J, I, O, J, I, T, Z, I, I, J, O, J, T, O, S, S, J, T, Z, S, I, Z, T, S, O, O, T, O, T, J, Z, L, S, T, T, L, T, J, L, T, I, J, T, S, L, T, O, J, O, L, S, L, L, Z, Z, Z, T, S, O, I, O, Z, J, J, Z, O, T, Z, O, L, I, J, L, Z, T, J, O, L, Z, J, J, L, T, S, T, Z, T, T, T, L, T, J, T, I, Z, Z, O, L, Z, T, Z, I, L, L, T, S, S, O, L, O, Z, S, Z, J, J, S, T, S, O, S, O, L, T, L, I, I, O, Z, I, S, Z, L, J, Z, S, J, L, I, T, S, T, J, J, O, J, T, T, O, J, L, T, I, Z, S, S, S, J, T, T, S, J, Z, L, S, L, S}
var g4 = [400]string{L, L, Z, Z, Z, T, S, J, I, S, L, O, L, L, S, T, T, J, Z, L, Z, I, J, J, O, O, Z, T, T, J, I, Z, I, I, J, J, O, O, Z, J, O, O, S, T, J, S, I, I, J, J, S, J, J, J, O, S, T, J, Z, L, T, O, L, S, L, I, I, T, T, T, I, I, L, S, J, J, T, S, S, S, T, J, L, O, O, S, O, Z, Z, S, L, T, S, L, L, L, T, S, Z, I, S, Z, J, O, I, O, S, S, T, I, O, O, L, J, S, S, I, Z, I, Z, I, O, J, S, T, J, L, T, T, O, J, L, Z, L, J, O, Z, I, J, J, J, I, O, Z, I, S, I, O, T, T, Z, I, L, O, Z, L, J, I, Z, J, O, S, O, J, I, J, J, I, J, O, T, O, L, S, O, T, I, O, S, I, J, J, O, T, O, S, J, O, Z, T, L, Z, T, S, O, O, J, L, I, O, O, I, L, L, J, O, T, S, Z, L, Z, Z, I, O, T, L, L, O, I, J, T, L, J, J, I, I, O, O, S, L, Z, L, Z, I, O, S, Z, S, T, Z, J, L, O, Z, T, S, I, L, S, L, S, T, J, T, S, Z, I, O, S, I, T, T, S, J, J, T, T, O, T, J, Z, J, I, Z, I, O, L, Z, J, T, S, I, T, I, S, O, S, T, I, O, I, L, S, S, S, T, O, T, T, O, J, S, S, J, Z, J, Z, J, O, J, T, O, Z, J, Z, Z, J, S, J, S, T, L, I, I, J, L, L, T, S, S, S, J, Z, L, J, T, L, S, L, Z, I, L, J, Z, J, L, T, L, Z, S, Z, O, J, J, S, T, T, S, O, I, L, T, Z, I, O, Z, T, O, S, L, T, T, L, I, J, O, L, I, I, I, T, J, J, Z, O, I, I, S, T, O, J, S, J, Z, O, O, L, L, J, S}
var g5 = [400]string{I, I, Z, J, Z, I, Z, T, S, O, I, O, S, L, S, O, Z, I, J, O, T, O, S, O, I, J, J, I, S, J, Z, L, J, S, L, O, Z, J, L, L, T, I, O, J, T, S, Z, O, O, O, S, L, J, Z, T, S, L, T, I, T, O, T, T, I, I, L, J, J, O, J, Z, J, O, O, O, J, J, Z, L, T, O, I, Z, S, Z, Z, T, L, S, L, L, J, J, L, Z, O, O, L, Z, I, J, O, J, S, Z, O, O, S, O, I, J, S, O, L, S, J, S, Z, Z, O, S, Z, O, S, J, S, I, J, T, T, Z, L, J, J, S, I, O, T, O, T, T, T, T, J, Z, L, J, O, I, L, I, T, Z, T, I, L, L, I, J, L, I, I, S, J, T, Z, T, I, S, O, L, L, T, L, L, T, T, Z, Z, S, J, L, L, O, Z, S, L, I, O, S, T, L, T, Z, L, S, I, T, L, S, O, T, T, L, J, T, T, J, S, J, L, T, J, Z, T, S, Z, J, I, I, I, I, Z, L, T, J, S, J, J, O, O, T, Z, Z, J, L, S, Z, I, S, J, I, J, Z, S, O, I, I, I, Z, T, J, Z, Z, Z, Z, T, I, T, T, Z, L, J, T, T, I, T, L, S, I, J, I, T, I, J, S, Z, J, Z, S, L, J, I, O, Z, Z, T, I, S, O, O, S, I, Z, O, Z, T, J, Z, S, Z, L, T, T, O, S, S, I, J, O, I, T, O, O, Z, J, O, S, I, Z, O, Z, Z, J, S, I, S, I, S, L, J, O, T, J, I, S, L, J, T, O, S, S, L, S, O, T, O, O, J, Z, S, S, Z, T, T, Z, J, I, S, L, O, Z, O, J, S, J, J, J, T, Z, L, T, J, I, Z, Z, S, T, Z, Z, O, Z, O, Z, S, S, S, O, T, O, T, Z, Z, L, S, I, S, I, J, I}
var g6 = [400]string{I, L, L, J, Z, I, O, J, S, L, I, O, I, T, T, J, J, S, S, O, I, O, J, Z, L, Z, L, I, L, I, L, O, L, S, Z, O, T, S, J, I, L, I, T, L, S, O, S, Z, J, T, Z, I, Z, O, Z, O, O, J, L, T, T, J, Z, J, T, O, J, T, J, I, S, I, T, L, Z, I, T, I, O, T, O, Z, T, Z, O, Z, Z, S, T, T, S, S, I, J, S, L, Z, S, S, O, Z, L, O, J, S, O, J, J, O, Z, J, S, L, I, O, I, T, T, I, Z, O, L, S, I, O, L, J, L, I, Z, O, T, S, J, L, Z, J, Z, J, O, Z, O, Z, T, J, Z, L, Z, L, Z, T, S, O, T, I, J, S, Z, S, O, T, I, O, T, S, J, T, J, O, I, I, L, Z, L, S, S, Z, I, I, S, T, J, I, Z, T, J, O, T, L, O, J, L, T, S, Z, O, I, J, S, S, Z, J, L, T, O, S, J, O, O, T, L, O, J, S, J, S, O, L, J, O, I, I, J, S, T, L, O, L, O, S, L, I, S, Z, Z, O, O, T, I, Z, T, J, J, L, T, J, T, S, Z, S, O, L, T, O, L, S, L, L, T, Z, T, I, T, O, L, Z, S, S, O, J, I, O, I, T, I, O, S, J, Z, L, O, O, T, S, J, O, S, L, Z, S, L, L, S, Z, I, J, L, O, Z, S, J, L, Z, I, Z, O, Z, T, O, O, T, Z, I, L, O, L, S, Z, J, Z, S, O, J, S, O, O, J, Z, Z, J, I, Z, S, I, S, O, T, J, S, S, O, S, I, L, O, Z, I, Z, I, I, I, O, S, T, T, O, L, O, I, O, I, Z, O, J, J, S, T, J, T, L, J, S, J, O, I, L, O, J, T, Z, S, I, I, Z, O, Z, S, T, O, I, T, J, J, T, Z, L, O, L, O, O}
var g7 = [400]string{O, L, Z, J, L, J, S, T, O, J, O, L, Z, Z, T, I, O, L, O, I, J, L, Z, Z, Z, T, L, L, S, Z, O, Z, L, J, S, J, J, S, T, O, Z, O, J, I, T, O, S, Z, I, T, J, Z, T, L, T, S, I, T, J, J, I, L, S, S, O, O, O, J, O, Z, O, I, Z, Z, L, L, S, O, Z, J, I, S, O, J, I, J, J, I, S, Z, T, S, L, O, T, J, S, J, I, Z, I, J, J, J, I, O, T, Z, Z, Z, Z, Z, I, S, S, T, J, I, O, S, J, J, I, I, L, O, O, I, T, J, L, I, Z, I, S, J, I, O, T, T, O, T, L, I, L, I, S, J, T, I, T, Z, I, O, O, O, L, J, J, L, J, T, S, T, O, L, T, I, I, O, J, I, Z, S, Z, S, L, I, L, I, T, I, I, S, O, J, Z, I, O, O, I, I, Z, J, Z, T, T, L, I, T, S, L, O, L, O, J, I, O, O, S, S, L, Z, S, I, O, I, S, I, Z, T, Z, L, O, I, L, I, I, I, L, Z, I, Z, L, S, L, T, O, T, S, L, J, T, T, S, T, L, S, Z, J, T, Z, T, O, L, T, T, T, S, J, L, O, J, Z, Z, J, T, Z, S, Z, Z, S, I, O, J, S, Z, L, O, T, I, Z, L, Z, T, Z, Z, I, O, L, L, O, S, I, T, L, O, S, J, J, O, O, Z, I, S, O, J, I, T, I, S, T, S, S, I, I, J, L, S, S, T, S, L, L, L, L, T, T, L, J, S, J, O, I, Z, L, Z, T, L, O, O, I, O, O, O, S, Z, T, T, T, Z, J, T, Z, J, Z, L, J, I, T, J, O, L, Z, T, T, Z, Z, I, L, I, S, Z, I, O, Z, T, T, L, J, O, T, S, S, I, O, S, J, L, Z, J, L, L, O, T, I, J, S, O, J}
var g8 = [400]string{Z, I, J, S, L, S, L, T, Z, S, O, I, I, L, O, S, S, S, I, L, O, T, Z, S, I, L, J, Z, S, Z, O, T, S, I, J, Z, L, S, T, Z, J, J, O, I, I, O, I, O, T, J, S, S, I, O, J, I, I, I, Z, I, Z, Z, S, J, T, S, S, I, J, I, Z, S, L, T, L, S, I, T, S, T, L, L, T, O, L, O, S, T, T, J, L, T, I, T, Z, L, I, O, J, T, L, Z, Z, I, T, T, J, Z, T, T, O, L, O, Z, S, I, Z, L, T, O, S, I, I, J, S, Z, I, T, T, S, I, L, O, Z, S, L, L, T, Z, L, J, O, S, T, S, J, L, I, S, S, L, L, T, Z, Z, L, O, L, L, L, Z, S, I, T, O, Z, L, L, L, J, L, I, L, I, O, T, S, T, O, O, S, I, J, Z, Z, L, O, I, O, L, L, T, J, S, O, I, O, O, S, O, T, J, J, J, T, L, S, Z, L, T, S, I, Z, I, I, S, L, S, T, J, S, T, Z, J, S, S, O, J, T, Z, O, Z, O, S, T, Z, I, T, O, O, T, J, I, O, L, I, O, Z, I, L, S, T, S, I, O, J, I, L, Z, S, Z, S, L, I, J, Z, I, T, T, Z, S, I, J, L, Z, Z, Z, S, S, L, T, Z, J, Z, T, T, O, T, S, O, T, I, T, J, J, Z, L, O, J, Z, T, O, T, O, I, Z, L, I, Z, O, T, J, J, O, O, S, T, Z, I, S, L, L, Z, I, S, O, Z, S, Z, Z, O, Z, Z, T, S, L, I, T, L, S, S, O, S, T, S, S, J, J, T, L, J, Z, L, O, I, T, I, S, L, T, Z, O, L, L, S, Z, O, T, S, I, L, T, S, I, T, I, L, T, L, L, L, L, T, T, I, I, J, T, Z, S, O, S, L, J, I, J, S, Z, O, J}
var g9 = [400]string{I, L, J, Z, S, S, S, I, Z, I, O, S, L, T, I, O, L, Z, L, I, J, J, I, S, O, Z, J, J, S, T, T, T, T, T, I, J, O, S, S, I, T, J, T, S, Z, O, I, S, S, J, O, Z, O, T, T, S, O, J, Z, T, S, Z, S, Z, J, S, O, J, Z, T, J, L, Z, S, S, T, T, O, T, O, O, S, L, O, L, Z, Z, T, T, S, Z, S, I, J, J, L, T, Z, O, J, Z, J, J, Z, I, L, I, O, J, I, O, S, L, I, Z, Z, I, Z, I, Z, Z, T, J, Z, J, L, O, O, I, S, Z, S, L, T, S, L, T, T, S, L, S, Z, O, T, J, T, T, L, O, Z, O, I, Z, J, O, I, L, L, O, O, L, O, Z, Z, J, J, S, J, J, J, S, J, S, T, L, Z, L, I, O, J, I, L, O, Z, O, L, I, L, Z, L, S, J, L, Z, J, O, Z, L, J, O, I, L, T, Z, L, S, S, O, L, L, J, O, S, I, Z, I, O, L, O, L, O, O, O, I, I, S, T, S, Z, S, J, J, J, L, O, I, O, Z, S, T, Z, O, I, J, J, L, O, T, S, L, L, Z, O, J, O, J, J, J, L, O, T, I, L, Z, I, I, O, Z, S, Z, Z, S, O, S, T, Z, I, L, L, O, I, J, L, O, J, I, Z, S, O, J, J, L, O, T, J, T, T, L, S, S, J, L, J, J, Z, I, Z, S, O, Z, I, I, L, O, I, S, Z, I, S, J, Z, T, O, Z, L, I, Z, T, L, J, J, Z, I, O, J, T, O, I, Z, L, Z, Z, S, Z, S, Z, Z, S, O, T, I, T, L, L, T, T, L, J, I, Z, S, J, Z, J, J, J, S, Z, L, O, O, I, T, Z, S, I, I, I, O, T, I, T, J, T, S, Z, S, L, O, L, S, Z, I, O, S, O, T, Z, J, L}
var g10 = [400]string{O, Z, J, S, O, Z, Z, Z, S, T, J, T, I, Z, J, I, J, L, I, J, O, Z, J, I, I, S, Z, Z, T, T, T, J, Z, O, L, Z, I, J, I, L, O, J, S, I, J, L, L, O, Z, L, Z, O, I, L, I, S, T, O, S, T, L, L, J, J, L, I, T, I, L, T, I, S, J, I, J, J, T, I, L, L, I, J, L, L, S, L, I, Z, Z, L, O, Z, I, I, S, J, I, O, J, Z, Z, T, J, Z, O, J, I, S, S, T, Z, O, T, I, Z, T, L, J, O, T, L, T, O, I, S, Z, T, Z, S, O, J, T, I, L, O, Z, L, O, O, L, S, O, Z, T, T, L, I, O, S, O, S, I, J, O, S, I, L, Z, I, O, L, Z, T, J, T, Z, J, J, L, O, T, O, L, T, L, O, T, L, L, Z, T, O, T, Z, I, S, I, Z, J, I, I, L, Z, Z, O, I, O, L, L, I, J, S, I, T, T, I, Z, L, O, Z, S, Z, Z, J, S, S, S, T, J, J, I, Z, Z, L, S, L, Z, T, S, I, Z, T, T, L, S, I, Z, Z, I, I, L, L, Z, L, S, L, T, Z, O, I, S, J, O, I, S, Z, Z, O, I, L, L, T, T, I, T, S, L, I, T, T, O, T, O, L, I, J, O, I, I, T, J, S, I, J, J, Z, Z, J, Z, L, T, O, L, J, Z, Z, J, J, Z, S, T, L, L, T, T, T, Z, O, I, S, T, Z, I, O, J, O, I, Z, S, T, L, Z, Z, Z, T, T, I, L, I, I, O, T, I, O, T, J, Z, L, S, L, Z, Z, T, Z, Z, T, Z, T, S, L, J, J, S, J, L, T, J, Z, I, T, I, L, Z, S, S, O, S, O, O, L, O, I, L, J, I, Z, Z, S, L, I, I, O, L, J, O, I, Z, S, I, L, Z, S, Z, O, O, T, Z, T, I, S}
var g11 = [400]string{S, J, O, T, I, L, T, L, J, I, T, I, S, T, O, S, O, S, J, S, S, I, Z, L, T, J, O, S, T, Z, J, T, L, Z, S, Z, I, S, Z, T, J, J, J, J, O, J, I, T, I, L, J, O, J, T, L, L, S, T, T, S, I, J, I, J, O, I, S, S, T, L, O, O, T, I, T, Z, I, O, O, O, I, T, J, T, J, O, J, J, O, L, S, L, S, S, T, Z, O, S, T, O, I, L, T, Z, O, S, O, L, L, I, L, Z, L, T, O, Z, L, S, L, J, S, Z, S, T, J, I, O, Z, J, I, J, J, J, O, J, T, I, Z, J, I, T, O, Z, J, O, L, I, S, O, Z, J, Z, I, T, J, J, I, L, Z, L, T, T, S, O, J, O, I, T, J, T, J, O, J, L, I, O, O, Z, O, O, I, I, Z, L, S, L, S, O, S, Z, S, Z, L, S, O, S, O, J, S, S, S, O, T, L, J, J, J, O, J, I, L, J, T, T, L, J, T, O, Z, J, S, Z, O, S, L, Z, S, I, J, Z, S, O, S, T, O, T, L, O, Z, Z, I, Z, S, S, J, O, T, L, O, O, O, S, Z, L, T, J, I, Z, T, Z, I, O, I, S, T, Z, J, J, L, Z, Z, T, O, O, S, T, Z, I, T, I, L, Z, Z, S, O, L, T, Z, J, J, I, O, O, J, J, O, S, Z, I, O, J, S, Z, O, S, L, Z, S, Z, Z, O, T, L, L, S, Z, O, S, T, T, S, T, T, Z, T, S, L, I, L, I, S, J, Z, T, L, S, Z, O, I, S, J, O, L, J, Z, I, L, T, Z, T, L, Z, Z, Z, I, I, Z, Z, J, I, I, L, S, I, L, L, Z, O, O, S, O, I, S, L, J, Z, Z, Z, Z, S, L, I, T, O, Z, Z, O, O, Z, J, T, S, O, L, Z, J, I, O, O, J}
var g12 = [400]string{I, L, T, O, O, T, T, Z, L, I, L, T, I, L, T, T, T, S, Z, J, L, T, J, J, J, Z, Z, T, I, Z, L, Z, L, O, L, S, Z, L, J, S, L, I, T, L, Z, S, I, I, I, I, S, Z, S, J, Z, Z, T, O, T, I, O, I, L, Z, L, Z, L, J, O, I, Z, T, I, I, T, I, J, J, T, O, J, J, I, Z, I, Z, S, T, O, J, L, T, J, I, Z, T, Z, Z, J, I, O, Z, O, J, I, O, S, S, J, O, S, L, J, J, L, S, Z, L, J, J, Z, L, T, I, S, T, T, T, L, I, S, I, J, I, I, J, T, L, S, I, T, I, J, O, L, T, J, T, L, S, L, I, O, I, I, Z, O, O, L, O, Z, I, Z, T, T, J, I, T, S, I, T, T, I, L, J, Z, I, T, O, L, S, S, J, O, Z, S, J, Z, S, Z, S, S, T, Z, J, I, L, I, Z, Z, T, I, J, I, L, Z, J, S, T, I, I, J, T, L, J, J, J, I, O, S, L, Z, T, L, I, T, T, O, J, J, S, T, L, T, O, O, J, O, T, S, Z, S, I, O, I, J, I, Z, Z, T, O, J, J, L, I, T, O, L, J, Z, O, Z, I, L, J, S, J, L, Z, S, S, L, S, I, S, J, Z, L, S, J, J, O, I, S, Z, I, Z, L, Z, J, I, J, Z, T, T, J, T, O, T, I, S, J, L, I, L, L, S, Z, T, T, S, T, L, Z, T, T, J, I, S, T, O, Z, L, Z, L, L, I, Z, I, T, I, S, S, J, O, L, Z, Z, S, J, S, J, T, T, T, O, S, J, I, I, O, S, O, J, Z, S, S, J, T, T, L, T, L, J, L, T, T, L, I, Z, I, L, Z, L, O, J, S, J, O, T, I, Z, T, S, I, O, L, Z, J, S, T, Z, Z, O, O, O, Z, I, L, J}
var g13 = [400]string{T, S, S, O, O, J, L, Z, O, J, O, O, O, J, L, Z, O, T, I, T, S, S, S, T, Z, S, I, S, O, T, S, T, J, L, S, I, O, O, J, T, J, S, O, Z, S, O, L, J, J, T, Z, L, L, I, L, L, L, L, S, Z, O, Z, Z, T, L, O, Z, O, L, O, O, T, Z, I, J, O, T, T, L, Z, I, J, I, O, I, I, O, J, Z, L, T, J, L, S, S, L, S, I, O, L, L, S, T, S, T, T, L, Z, T, L, L, J, I, I, T, O, T, Z, S, J, L, L, J, S, J, T, I, S, L, J, I, Z, J, S, I, O, O, J, O, J, I, T, T, T, O, S, L, L, T, S, L, T, T, S, L, S, T, S, L, T, Z, Z, T, L, T, J, I, Z, O, S, S, Z, O, T, T, J, Z, J, I, T, Z, J, L, Z, L, J, I, Z, J, O, L, J, T, L, O, O, J, T, Z, I, J, L, O, Z, I, Z, I, Z, I, J, I, O, O, T, I, T, O, L, L, Z, Z, J, O, T, Z, J, T, J, L, O, S, T, Z, T, J, O, L, T, Z, I, L, T, J, T, T, Z, O, Z, S, O, I, S, T, L, Z, I, L, S, O, O, L, O, J, I, T, I, Z, O, S, I, Z, I, L, O, I, I, O, O, T, S, J, T, O, L, J, S, Z, T, S, L, J, J, J, I, S, T, Z, Z, O, S, Z, S, Z, Z, Z, J, L, T, O, L, T, I, O, Z, I, J, J, S, T, Z, O, T, O, T, T, L, I, J, O, J, L, Z, Z, O, O, J, J, J, Z, J, Z, L, L, T, T, O, T, O, L, Z, S, T, I, T, Z, L, Z, Z, Z, S, O, I, I, J, I, S, S, J, Z, L, S, T, T, S, J, J, J, S, O, O, J, L, Z, T, I, L, I, J, Z, T, O, O, O, O, J, L, O, T, I, O}
var g14 = [400]string{L, L, T, J, S, T, J, O, L, O, Z, T, L, I, O, S, T, O, O, Z, I, L, I, Z, J, L, I, I, T, S, T, O, Z, Z, Z, O, J, I, J, O, L, L, L, J, Z, S, O, T, Z, T, T, T, S, I, O, S, T, Z, L, J, S, J, T, O, O, I, O, T, Z, Z, S, O, Z, O, S, S, L, I, S, I, I, J, J, J, O, I, I, J, J, L, T, S, S, S, Z, J, J, O, Z, T, Z, I, O, L, S, Z, O, I, I, I, Z, J, J, I, O, Z, S, Z, I, L, Z, S, T, J, I, O, Z, J, J, T, T, O, J, L, J, J, S, T, I, J, O, J, O, L, O, Z, I, I, J, I, J, T, J, O, I, T, O, Z, O, J, T, L, Z, J, O, S, Z, T, T, Z, I, Z, T, L, I, L, L, I, Z, Z, S, Z, L, J, Z, S, T, Z, S, Z, S, T, I, T, O, O, T, T, T, Z, J, T, S, O, S, Z, J, S, I, T, I, T, S, T, T, T, O, O, T, L, J, L, L, T, O, S, S, L, S, Z, J, T, J, L, L, I, L, T, J, L, L, O, S, L, T, Z, Z, S, L, S, J, Z, T, L, T, J, Z, S, O, J, L, L, J, L, T, I, J, I, Z, L, L, S, T, Z, O, I, I, O, J, I, J, I, S, O, L, J, Z, Z, T, Z, S, T, T, J, L, S, S, J, L, S, I, J, Z, I, J, T, J, O, Z, S, J, S, O, Z, I, O, J, Z, Z, Z, I, L, T, I, O, Z, J, J, O, L, S, Z, I, L, J, O, L, T, S, J, I, L, Z, J, T, I, I, Z, I, O, O, I, S, T, O, J, L, Z, J, T, S, T, Z, S, J, Z, L, T, I, L, S, L, J, Z, I, I, Z, O, Z, J, Z, S, S, T, J, O, L, J, L, Z, J, O, S, O, Z, O, T, S, J, L}
var g15 = [400]string{L, S, O, J, L, Z, O, L, I, S, T, I, L, O, I, L, I, S, Z, S, Z, L, J, J, I, Z, O, L, Z, T, Z, L, L, O, I, S, I, L, J, S, J, Z, L, O, I, Z, T, J, L, T, I, I, I, Z, I, J, Z, L, Z, J, I, T, Z, L, S, S, O, Z, J, Z, O, Z, L, O, I, T, J, T, J, I, S, T, T, T, I, Z, Z, J, O, I, L, J, O, J, O, S, J, I, I, S, J, Z, L, S, S, J, O, S, I, I, S, O, O, I, T, Z, O, O, T, O, L, I, O, T, Z, T, Z, I, O, S, S, O, T, T, T, J, S, S, O, O, L, Z, T, L, S, Z, Z, O, S, Z, L, Z, O, Z, O, Z, T, S, O, T, I, J, J, Z, O, O, S, S, J, T, L, Z, J, T, Z, S, S, O, S, I, J, O, J, Z, O, S, L, T, T, S, O, O, S, I, L, J, S, O, Z, J, I, J, L, O, T, L, S, Z, L, O, L, Z, Z, O, I, T, S, J, T, Z, L, Z, I, Z, I, O, I, I, L, S, S, L, T, J, J, L, J, T, L, I, S, J, I, I, O, O, L, Z, T, S, Z, T, Z, O, L, I, J, S, J, S, J, Z, O, T, I, T, I, I, T, J, O, O, I, I, Z, T, O, I, J, S, T, J, O, T, I, J, I, T, T, J, O, S, J, T, J, Z, I, T, J, I, J, J, I, S, L, S, T, S, L, S, I, I, O, O, I, S, I, S, S, O, J, S, Z, S, T, I, T, S, O, I, I, O, J, O, S, S, Z, Z, T, O, I, J, L, T, T, J, I, T, O, Z, Z, T, S, T, J, T, S, Z, O, T, O, S, T, S, J, L, I, S, I, I, O, I, Z, I, O, J, I, I, T, S, Z, S, L, T, J, Z, J, I, J, S, S, O, L, O, L, I, T, L, I, I}
var g16 = [400]string{T, J, Z, Z, J, I, T, T, I, O, Z, T, L, S, O, I, J, T, O, O, T, I, O, O, T, J, S, T, O, T, O, O, I, Z, J, Z, Z, L, I, I, Z, J, T, S, O, S, S, O, J, S, I, I, T, S, Z, I, I, I, I, S, J, Z, Z, L, O, T, L, L, S, J, L, L, Z, I, T, S, T, I, L, Z, T, I, I, S, O, I, I, J, J, I, I, S, S, O, I, J, S, I, I, T, L, Z, J, J, Z, S, S, J, O, L, J, T, I, Z, T, T, Z, I, O, O, L, I, J, J, L, J, L, Z, J, O, Z, O, L, J, T, J, J, I, Z, J, Z, J, Z, O, Z, I, S, L, J, O, Z, J, J, J, S, L, L, Z, J, J, J, O, J, I, Z, I, O, S, T, S, T, L, S, O, T, I, Z, S, J, S, Z, T, T, T, L, T, L, S, L, T, J, O, L, S, Z, Z, J, T, Z, J, I, L, S, Z, L, I, Z, S, Z, L, O, I, T, T, T, I, T, L, I, S, T, S, J, T, J, O, T, I, L, O, L, I, Z, J, T, L, I, I, S, Z, Z, J, L, Z, O, I, Z, L, Z, L, I, Z, S, Z, L, Z, O, J, I, T, O, S, T, I, Z, J, L, J, T, Z, S, J, S, Z, J, I, I, J, S, I, Z, I, I, I, S, L, O, O, Z, I, L, L, J, T, T, O, O, T, O, L, S, I, J, I, J, Z, O, Z, I, S, T, J, T, J, J, J, J, S, S, J, L, J, I, O, T, S, T, Z, S, L, S, T, T, L, L, J, J, J, I, O, T, S, I, T, T, Z, L, L, L, L, T, O, T, I, T, I, I, T, I, T, T, Z, I, I, S, Z, J, J, T, O, Z, Z, S, O, T, T, I, S, T, I, Z, J, S, S, O, J, T, L, O, T, S, T, L, J, Z, O, I, S, L, S}
var g17 = [400]string{Z, L, J, T, J, J, I, Z, I, T, O, L, I, I, L, O, J, O, S, O, L, O, J, S, S, T, J, J, Z, I, S, T, T, T, L, I, O, O, I, J, J, O, T, S, J, L, Z, J, J, L, L, L, S, L, L, O, S, O, S, I, O, J, L, Z, I, O, O, L, L, I, O, L, J, L, Z, Z, S, Z, L, S, Z, S, J, S, L, L, I, T, S, L, O, Z, L, Z, I, J, L, S, L, Z, J, I, J, S, O, S, O, I, O, T, L, Z, T, T, Z, O, S, I, O, J, S, O, T, L, I, T, Z, Z, J, L, I, O, I, J, O, S, I, O, J, T, L, Z, L, O, Z, Z, I, Z, T, J, L, O, O, I, O, Z, L, O, T, S, S, L, T, T, Z, L, J, L, I, L, I, L, J, J, O, O, S, J, I, I, O, Z, O, J, O, T, Z, T, T, S, T, O, O, I, T, Z, T, Z, L, T, T, Z, I, Z, O, S, J, Z, T, I, S, T, T, O, L, S, L, L, L, O, Z, O, J, Z, S, T, T, I, L, L, J, J, I, O, L, O, L, I, I, T, T, Z, O, I, J, O, J, O, J, S, L, O, J, Z, O, S, J, O, J, Z, J, Z, J, O, L, T, J, T, T, S, I, Z, L, O, T, I, T, Z, S, S, I, L, O, O, J, J, S, I, J, J, O, T, J, S, S, L, L, O, Z, J, O, I, T, S, T, L, S, Z, L, I, T, J, Z, Z, Z, L, S, O, Z, I, I, Z, T, L, L, Z, Z, I, T, Z, S, S, I, S, O, T, S, T, Z, L, L, I, O, O, Z, O, O, S, L, Z, Z, T, L, J, O, T, O, T, L, I, L, S, I, J, T, L, O, S, I, S, I, Z, Z, J, L, T, L, I, I, I, L, I, O, O, O, J, I, L, T, O, L, O, J, J, O, Z, T, L, O, S}
var g18 = [400]string{L, J, I, O, O, I, S, O, S, S, J, S, I, O, S, T, I, J, S, Z, S, J, I, T, T, T, Z, S, S, L, S, J, I, Z, T, L, T, L, Z, S, L, I, O, Z, J, S, S, T, I, L, Z, T, O, J, L, T, Z, Z, T, S, L, O, T, T, O, L, L, O, S, J, O, I, O, L, L, I, O, O, J, T, O, T, L, O, S, J, Z, T, S, J, O, L, J, Z, I, S, L, Z, O, Z, I, O, J, L, O, O, J, Z, S, L, T, T, J, Z, S, T, Z, I, J, S, Z, L, L, S, Z, I, Z, J, L, S, S, S, L, S, T, S, O, I, O, O, I, J, S, O, Z, T, J, Z, T, O, S, S, T, J, I, Z, O, Z, I, S, T, J, Z, J, T, T, Z, Z, S, L, L, Z, L, T, Z, I, O, O, T, O, O, T, J, I, S, L, J, S, T, J, I, Z, L, T, T, J, T, L, T, S, Z, Z, O, I, I, O, J, Z, Z, T, T, J, I, I, S, S, S, L, S, O, J, O, S, Z, L, T, Z, S, S, L, J, O, T, J, L, T, I, O, Z, I, Z, Z, I, L, L, O, T, O, T, L, L, I, Z, L, J, S, S, L, O, O, I, T, L, Z, O, L, S, Z, I, L, S, I, J, J, O, S, S, Z, J, Z, L, T, O, Z, L, I, O, J, L, I, Z, O, J, L, J, I, J, J, L, S, O, I, T, T, Z, O, L, O, O, T, L, I, I, Z, J, T, J, Z, S, Z, O, S, I, T, S, O, L, L, I, S, Z, J, L, S, J, T, S, S, I, T, J, J, O, O, S, O, T, T, Z, J, T, Z, O, Z, J, S, J, T, I, I, T, J, O, Z, S, Z, S, J, L, L, Z, Z, L, S, Z, I, O, S, I, I, Z, Z, J, Z, L, T, S, O, T, T, I, L, T, S, O, J, L, T, S, L}
var g19 = [400]string{S, I, Z, I, T, L, J, S, O, S, Z, O, Z, L, L, S, T, L, O, T, O, L, J, I, I, O, I, S, T, Z, S, S, J, Z, L, T, J, O, Z, Z, S, L, Z, J, T, J, I, L, Z, S, T, O, J, T, L, Z, S, T, S, J, S, S, I, T, J, J, L, T, J, I, L, O, T, I, J, O, I, L, L, S, Z, L, I, L, J, Z, L, O, L, O, T, I, O, I, Z, T, I, I, J, L, O, Z, O, T, Z, J, O, L, J, J, J, J, S, O, S, I, Z, J, I, I, L, J, Z, Z, I, L, O, O, S, O, I, O, L, O, S, T, S, L, S, I, O, J, O, S, I, L, L, T, L, S, I, Z, J, L, S, O, L, L, S, J, S, O, O, Z, T, O, J, L, I, J, L, J, L, L, S, J, O, O, O, I, Z, S, T, L, I, Z, J, I, I, T, L, O, J, T, J, I, L, J, O, S, I, T, J, L, Z, S, L, T, L, T, S, O, J, I, L, S, J, I, Z, J, I, I, Z, J, O, S, Z, L, Z, S, T, I, T, O, T, O, L, J, Z, T, S, S, O, S, T, Z, Z, O, S, J, S, T, O, I, Z, T, I, Z, I, Z, T, T, J, L, I, J, S, T, I, S, I, T, T, L, J, O, L, O, O, I, J, T, Z, L, L, I, T, O, L, I, I, L, Z, I, T, I, O, O, I, S, Z, I, T, J, O, L, J, S, J, Z, O, O, O, L, J, T, S, S, T, J, S, J, Z, L, S, J, Z, O, S, I, L, L, Z, L, I, J, T, I, O, O, O, S, J, I, T, J, Z, Z, Z, T, S, L, T, I, I, T, S, T, Z, Z, Z, S, T, I, L, O, S, S, I, L, Z, Z, Z, I, J, L, O, O, J, L, J, S, L, O, L, I, Z, J, Z, I, J, S, Z, L, I, L, I, J, O, J}
var g20 = [400]string{I, T, J, Z, I, J, Z, O, O, S, S, Z, S, T, S, I, L, S, O, S, Z, J, O, I, L, J, S, J, Z, O, L, T, J, L, S, O, L, I, O, Z, T, L, J, Z, O, I, S, J, I, Z, L, Z, J, O, J, Z, O, O, L, J, I, O, T, S, Z, I, I, I, O, I, S, S, J, I, I, Z, S, J, I, S, O, T, O, S, I, Z, J, T, S, I, O, J, I, S, O, L, Z, L, T, T, J, S, T, T, O, J, I, T, J, Z, T, L, L, J, L, T, S, S, J, S, J, L, J, O, L, L, T, O, S, L, Z, T, L, T, J, L, O, O, T, O, S, Z, I, S, I, I, S, I, Z, L, I, L, J, O, S, J, L, Z, L, L, Z, T, L, T, O, S, T, L, Z, T, S, J, J, S, S, Z, I, O, J, T, T, I, O, L, Z, S, O, O, Z, O, J, O, L, L, J, J, S, I, S, J, Z, T, S, O, L, T, Z, L, L, Z, L, T, S, S, L, J, O, O, Z, J, S, S, I, O, J, L, J, I, I, I, O, L, O, J, J, S, Z, I, Z, Z, L, S, J, I, L, O, J, S, L, Z, T, J, T, J, I, Z, O, L, L, J, J, Z, J, S, Z, L, T, L, O, O, I, L, T, I, I, L, L, S, O, S, O, Z, L, L, S, J, J, O, T, Z, O, Z, J, S, S, O, O, L, O, Z, L, T, O, O, S, L, T, S, S, I, L, T, S, J, I, I, Z, O, T, T, L, J, I, J, J, T, J, O, L, J, I, O, I, Z, I, O, J, S, O, Z, O, T, S, I, S, I, T, L, O, J, L, J, J, S, Z, I, J, S, I, O, O, I, T, T, S, L, S, O, T, I, I, Z, S, T, O, Z, J, L, S, I, Z, L, J, S, J, S, I, O, O, Z, Z, Z, T, J, T, I, O, S, Z, T}
var g21 = [400]string{O, T, L, S, Z, L, L, J, T, J, I, L, Z, J, O, L, O, L, J, L, Z, T, J, O, T, T, S, S, I, S, I, I, I, Z, T, O, O, I, O, T, J, J, Z, J, I, L, T, J, T, S, O, Z, Z, O, S, J, J, T, L, O, L, L, L, I, J, T, O, L, T, S, O, O, I, O, O, I, T, T, L, L, J, L, I, J, I, L, J, J, S, Z, Z, S, L, L, S, O, S, I, J, S, Z, Z, L, I, Z, S, J, Z, T, O, S, J, J, O, J, L, Z, O, J, S, L, L, O, S, L, J, S, T, Z, O, S, L, S, Z, J, I, T, S, I, O, L, O, O, Z, J, S, S, S, O, Z, O, L, T, Z, J, O, L, Z, Z, L, L, Z, Z, O, S, T, L, O, S, L, Z, O, Z, Z, L, J, J, L, Z, I, I, O, I, Z, I, I, I, I, J, L, O, T, O, I, O, S, L, Z, O, I, L, L, I, S, L, Z, O, S, J, T, O, T, L, J, Z, J, T, I, O, Z, L, J, I, T, S, S, L, O, J, I, S, Z, S, S, T, I, L, J, J, I, T, S, T, T, T, J, Z, Z, T, I, J, I, I, T, O, S, Z, O, T, S, T, Z, O, S, L, L, J, Z, I, Z, I, T, J, Z, I, Z, L, I, T, L, S, O, T, O, Z, L, S, Z, I, I, L, T, J, Z, Z, S, O, I, I, L, J, Z, T, T, L, O, T, L, L, L, L, I, S, S, J, S, J, T, L, L, I, I, J, I, L, L, O, S, J, J, L, O, J, O, I, T, L, Z, L, T, O, L, J, I, T, I, L, L, J, L, S, I, I, I, S, Z, L, L, S, Z, T, S, L, I, T, L, T, T, L, Z, T, J, O, L, O, L, O, J, Z, S, O, S, S, T, I, J, T, J, Z, T, Z, S, S, S, T, T, T, S, Z, O}
var g22 = [400]string{I, I, T, J, T, L, J, S, L, J, T, L, Z, J, J, S, T, J, T, S, O, O, T, J, L, O, T, Z, Z, T, L, Z, L, S, T, L, T, I, T, J, O, O, T, L, T, T, J, O, S, S, T, Z, O, Z, J, L, I, O, J, J, Z, O, S, S, Z, S, T, T, J, J, L, L, I, S, Z, I, T, Z, L, L, S, S, T, T, S, J, S, I, L, L, L, T, I, J, T, O, L, L, Z, Z, J, S, Z, L, O, O, T, Z, O, S, I, O, I, S, Z, J, I, I, O, Z, T, T, O, S, Z, S, T, Z, T, S, L, T, S, O, L, I, L, I, O, S, L, S, L, Z, S, S, O, I, S, T, O, L, L, Z, O, L, J, L, T, J, I, O, T, J, L, S, S, J, J, I, L, Z, J, S, I, S, J, O, T, O, L, O, Z, Z, T, L, O, J, S, T, L, Z, I, I, T, O, S, L, L, J, L, L, O, I, O, I, Z, I, O, S, S, T, S, S, O, S, I, I, T, S, J, I, Z, S, T, I, Z, T, O, L, L, S, I, S, Z, L, O, L, T, I, T, S, J, L, J, L, O, J, Z, O, S, T, Z, T, L, S, T, Z, O, I, I, O, I, O, I, O, L, O, J, S, O, J, Z, J, I, Z, I, J, T, S, O, J, S, S, O, L, S, J, J, Z, O, T, J, Z, J, O, L, O, J, O, O, T, Z, I, O, Z, Z, L, I, Z, I, J, Z, J, J, I, O, L, T, Z, O, L, J, L, S, I, L, O, Z, O, I, J, O, T, S, J, O, S, Z, L, I, L, S, Z, O, I, L, J, L, I, J, L, I, Z, L, I, T, S, Z, T, O, L, O, S, S, L, Z, Z, I, T, Z, S, L, L, L, T, L, S, T, I, T, S, O, J, Z, I, O, Z, S, T, Z, Z, O, J, Z, J, O, L, L, L}
var g23 = [400]string{Z, O, Z, T, I, T, J, J, T, O, J, S, O, S, Z, Z, Z, O, I, S, S, L, I, J, L, S, Z, O, O, T, S, J, I, J, J, Z, T, J, T, J, S, T, T, O, O, T, S, S, O, O, T, T, I, Z, I, Z, Z, Z, S, Z, L, Z, O, I, T, J, T, Z, Z, J, J, O, J, O, I, T, T, O, S, Z, T, Z, Z, O, I, T, J, O, J, O, J, I, Z, I, Z, T, Z, L, O, Z, J, S, O, T, L, T, J, I, J, T, J, Z, Z, L, S, J, I, Z, O, J, S, Z, L, I, L, Z, J, S, L, J, J, S, O, I, J, L, O, Z, J, Z, Z, T, I, O, O, S, L, I, L, T, Z, T, Z, Z, S, S, I, L, S, J, S, T, L, S, Z, O, O, Z, S, L, S, O, I, Z, Z, L, L, J, O, L, T, T, J, O, L, S, J, J, T, S, L, J, I, J, J, L, O, T, L, J, T, Z, J, Z, T, T, Z, I, L, S, J, T, L, O, S, J, O, T, L, O, J, S, I, Z, Z, T, O, Z, J, S, S, Z, Z, Z, O, O, I, O, O, S, O, I, T, Z, L, J, J, I, Z, Z, Z, T, L, S, J, S, L, J, T, I, J, L, I, S, T, I, J, L, S, J, S, Z, J, T, O, Z, I, S, T, S, T, I, L, Z, O, Z, J, L, T, J, T, I, T, Z, S, O, O, Z, I, L, J, T, J, L, I, I, J, L, L, Z, O, T, I, J, L, I, O, O, J, T, J, O, I, S, O, I, S, I, T, I, T, Z, L, S, J, J, J, L, S, I, Z, O, S, S, L, L, S, I, L, I, S, Z, S, I, I, Z, I, Z, L, L, T, Z, I, L, O, T, S, S, O, T, Z, Z, I, T, J, T, I, O, T, J, S, S, O, T, L, J, J, O, L, J, T, O, I, O, O, T, Z, Z, J, L}
var g24 = [400]string{S, J, S, I, Z, Z, I, J, O, T, S, T, L, J, L, Z, Z, L, I, J, Z, L, J, S, L, Z, T, L, J, T, T, S, J, J, Z, Z, I, Z, T, Z, Z, Z, T, T, J, I, I, L, I, I, Z, T, Z, L, O, S, Z, O, J, L, Z, I, I, O, S, T, O, Z, J, J, Z, L, I, J, I, Z, I, L, I, I, T, S, J, I, T, S, Z, S, J, Z, T, L, Z, T, S, J, Z, O, O, I, S, I, O, J, I, L, Z, L, L, Z, I, S, I, O, O, I, Z, J, O, T, L, I, L, L, S, S, L, O, O, I, S, T, L, O, Z, T, J, L, L, T, J, I, T, L, S, S, S, Z, S, J, Z, J, Z, Z, O, J, S, I, L, Z, Z, J, O, Z, Z, I, L, Z, J, Z, L, T, L, Z, J, Z, J, J, T, S, S, J, I, T, J, T, L, Z, O, S, T, L, S, I, J, I, L, L, S, O, S, T, I, Z, J, J, I, S, O, I, O, O, Z, S, T, O, I, J, J, Z, S, L, Z, Z, T, L, I, O, O, S, T, T, L, S, I, J, I, T, T, T, T, T, O, J, O, S, T, O, Z, L, O, Z, Z, Z, O, J, Z, O, J, Z, J, L, T, S, L, I, J, I, Z, T, J, L, I, O, T, L, I, L, J, S, T, T, L, T, S, J, I, I, Z, L, T, T, T, Z, Z, O, I, O, S, S, I, Z, T, O, O, T, L, Z, I, L, S, I, T, S, Z, T, I, J, Z, I, O, Z, Z, T, I, I, Z, I, Z, Z, O, S, Z, S, L, O, T, T, T, S, J, I, T, S, O, Z, L, O, O, S, T, I, L, L, I, Z, O, I, T, J, Z, T, O, S, I, J, I, T, I, T, J, T, L, I, I, O, L, L, L, S, O, O, I, I, O, O, J, O, Z, Z, L, O, Z, O, I, J, J, S, T, J}
var g25 = [400]string{J, S, S, I, Z, T, T, O, T, Z, I, J, Z, J, L, J, T, Z, I, Z, J, Z, S, L, T, S, O, Z, J, S, L, O, L, O, Z, L, T, S, L, S, Z, L, O, Z, O, I, I, J, L, L, S, O, S, S, S, S, O, O, O, T, O, O, Z, T, Z, S, J, T, S, I, Z, J, S, S, S, O, S, S, I, S, T, O, S, O, T, T, O, Z, I, S, Z, L, J, I, T, T, S, Z, L, Z, T, O, L, J, I, J, O, Z, I, O, J, O, Z, T, L, Z, S, S, S, L, J, S, O, I, J, T, J, O, S, Z, S, O, J, T, Z, T, Z, S, O, Z, S, L, O, I, J, L, O, T, O, O, I, S, I, L, Z, J, O, L, J, I, O, Z, L, T, L, T, T, T, Z, J, O, L, Z, I, Z, I, L, O, J, S, S, L, I, Z, J, O, S, T, Z, O, L, Z, Z, I, I, I, L, S, T, L, I, O, T, S, O, I, T, Z, T, L, T, T, T, O, I, Z, S, T, L, I, Z, Z, I, T, O, S, L, S, J, Z, J, S, T, S, L, Z, J, O, L, T, I, S, L, Z, T, S, L, L, T, L, I, Z, J, J, S, J, Z, O, J, L, I, L, S, S, J, I, I, I, Z, S, T, S, O, O, O, J, J, J, O, T, S, L, I, S, S, O, L, J, S, I, O, L, L, Z, T, I, O, J, L, O, Z, O, O, L, S, Z, L, T, Z, T, L, L, S, I, Z, O, T, S, Z, L, L, Z, O, S, J, L, L, I, L, J, S, I, S, S, L, I, T, S, Z, I, J, T, J, Z, S, O, I, I, L, Z, O, O, L, J, T, Z, I, L, L, S, S, S, Z, J, Z, Z, L, L, T, I, S, I, S, L, L, I, I, Z, O, T, S, I, L, L, O, Z, T, Z, S, Z, L, I, J, J, O, S, Z, L, T, I}
var g26 = [400]string{I, J, Z, I, L, T, S, S, I, T, J, Z, O, S, Z, O, Z, J, O, Z, T, I, Z, I, O, S, T, Z, L, S, O, J, L, J, I, J, S, S, T, J, T, Z, T, Z, O, I, Z, Z, I, Z, T, L, T, J, T, J, I, Z, I, L, S, L, J, S, I, O, L, T, Z, J, O, Z, I, T, J, O, S, O, S, J, Z, L, J, J, J, Z, T, L, J, Z, O, O, T, T, I, Z, T, Z, L, S, L, Z, I, T, Z, T, L, Z, L, S, O, Z, L, S, L, O, J, T, S, L, J, S, S, I, I, S, L, Z, J, Z, I, I, Z, I, I, I, S, Z, Z, O, S, L, J, J, Z, J, J, S, S, T, O, I, S, J, J, L, S, I, J, I, Z, I, S, S, L, S, J, O, I, J, J, S, L, Z, J, Z, L, I, T, L, Z, S, Z, O, O, T, I, T, L, I, L, L, Z, L, S, I, O, O, I, I, L, S, O, J, S, O, I, I, I, S, Z, L, L, J, L, Z, L, S, T, L, O, L, I, L, S, O, I, Z, I, Z, Z, Z, Z, I, L, I, S, T, O, I, S, T, O, O, S, L, J, T, O, J, T, I, S, Z, O, I, J, O, T, Z, Z, Z, J, I, Z, S, S, O, L, T, J, T, J, L, L, Z, L, L, J, I, T, I, I, L, O, L, L, L, Z, Z, O, S, J, I, J, S, O, T, O, Z, I, T, Z, I, O, L, T, I, O, S, S, L, T, I, I, L, L, J, Z, I, J, I, I, J, I, S, L, Z, Z, I, S, J, S, J, O, S, L, J, J, I, O, O, O, T, J, L, T, Z, O, I, I, I, L, I, L, Z, I, I, Z, O, S, I, T, S, S, I, L, I, T, S, J, L, J, S, L, O, I, O, J, L, S, S, O, Z, J, Z, T, Z, J, J, I, S, J, I, L, S, S, I, Z, I}
var g27 = [400]string{O, S, T, T, T, J, S, O, I, T, I, O, J, T, T, T, O, S, T, L, O, S, S, O, I, L, O, I, S, Z, L, I, Z, O, Z, J, T, O, O, S, L, L, T, S, I, S, S, S, O, O, I, Z, O, O, J, I, S, J, T, O, L, Z, I, J, I, S, L, T, L, L, O, O, L, Z, T, S, T, O, J, S, O, T, J, S, T, L, T, Z, J, T, J, T, I, O, O, I, Z, J, I, L, L, L, Z, O, Z, T, I, S, T, L, J, I, O, T, S, L, J, I, L, Z, S, O, I, T, I, L, Z, S, Z, T, O, I, T, Z, Z, O, I, T, Z, L, I, T, L, O, S, I, T, Z, S, O, O, O, T, L, I, J, Z, O, T, L, I, L, Z, T, T, J, I, S, S, L, S, Z, O, I, J, O, S, J, Z, S, I, O, J, L, Z, T, O, O, I, O, L, T, O, S, T, Z, O, Z, L, L, J, J, Z, I, S, Z, L, Z, Z, I, J, L, I, T, I, I, S, O, O, I, Z, T, L, L, S, J, Z, L, I, S, I, I, L, I, S, J, I, Z, T, S, S, J, O, Z, Z, L, I, J, J, T, L, Z, L, O, T, T, Z, T, I, S, O, S, T, S, I, T, S, O, I, L, O, Z, Z, J, T, S, Z, T, I, S, T, O, T, O, S, O, T, O, L, J, L, Z, O, L, L, T, I, J, Z, L, J, T, I, T, T, T, S, Z, Z, T, Z, S, O, J, O, T, L, Z, I, I, J, L, T, T, J, Z, J, S, L, S, S, J, S, S, S, I, L, I, O, Z, L, S, I, T, S, Z, S, I, S, O, Z, S, L, S, S, T, L, S, L, L, Z, S, J, Z, T, I, J, J, I, O, I, T, O, J, Z, L, I, L, I, S, Z, O, T, O, O, J, T, S, O, T, O, S, I, Z, O, I, I, J, I, L}

var gr1 = [60]int{9, 9, 9, 7, 7, 4, 2, 7, 9, 2, 9, 7, 8, 0, 5, 3, 5, 0, 6, 6, 5, 8, 1, 1, 6, 4, 3, 1, 2, 2, 5, 4, 6, 0, 9, 6, 3, 1, 0, 7, 9, 9, 1, 8, 2, 8, 7, 5, 7, 7, 1, 9, 9, 5, 1, 0, 3, 3, 5, 2}
var gr2 = [60]int{3, 1, 2, 0, 2, 2, 1, 3, 9, 5, 1, 0, 4, 3, 1, 3, 0, 4, 3, 6, 7, 0, 2, 4, 3, 0, 8, 7, 8, 0, 8, 8, 6, 1, 1, 2, 4, 1, 6, 5, 8, 2, 7, 8, 5, 4, 8, 9, 3, 9, 6, 2, 9, 2, 0, 4, 5, 1, 7, 2}
var gr3 = [60]int{9, 8, 3, 1, 1, 5, 1, 7, 2, 2, 9, 0, 1, 7, 4, 0, 8, 4, 5, 3, 6, 5, 7, 1, 1, 0, 7, 4, 4, 1, 0, 1, 3, 9, 6, 0, 8, 1, 8, 9, 0, 3, 6, 2, 0, 3, 7, 9, 5, 8, 2, 8, 7, 4, 1, 0, 1, 0, 2, 7}
var gr4 = [60]int{1, 6, 1, 7, 7, 2, 3, 8, 8, 7, 3, 3, 8, 6, 3, 3, 2, 5, 0, 1, 8, 9, 5, 9, 5, 3, 6, 4, 2, 0, 9, 4, 0, 6, 1, 1, 4, 2, 0, 4, 7, 4, 6, 7, 6, 1, 0, 2, 6, 5, 5, 7, 7, 9, 7, 0, 9, 0, 7, 6}
var gr5 = [60]int{0, 7, 2, 3, 7, 4, 5, 5, 0, 0, 0, 0, 9, 5, 0, 9, 7, 3, 3, 2, 2, 2, 2, 5, 3, 0, 3, 8, 2, 1, 7, 1, 1, 1, 0, 1, 8, 8, 2, 1, 9, 7, 7, 1, 3, 3, 4, 4, 7, 0, 0, 8, 3, 9, 6, 8, 2, 3, 4, 0}
var gr6 = [60]int{7, 6, 1, 6, 3, 1, 5, 8, 6, 4, 1, 2, 2, 3, 7, 9, 3, 7, 2, 0, 7, 0, 7, 5, 3, 2, 3, 1, 7, 1, 5, 2, 2, 3, 5, 1, 0, 5, 1, 0, 6, 8, 5, 8, 8, 9, 4, 6, 7, 2, 3, 7, 3, 9, 7, 4, 6, 2, 3, 2}
var gr7 = [60]int{3, 7, 4, 8, 1, 5, 7, 8, 6, 1, 7, 9, 9, 7, 1, 6, 4, 1, 6, 6, 8, 5, 3, 5, 7, 2, 2, 9, 4, 4, 1, 7, 5, 1, 9, 7, 1, 2, 7, 0, 7, 3, 0, 6, 2, 7, 2, 2, 5, 1, 1, 5, 9, 2, 2, 6, 8, 6, 0, 5}
var gr8 = [60]int{3, 0, 4, 3, 4, 8, 4, 6, 0, 9, 6, 2, 2, 2, 8, 7, 3, 5, 8, 4, 6, 8, 5, 8, 5, 6, 2, 6, 0, 3, 3, 3, 2, 9, 2, 9, 1, 7, 3, 3, 2, 1, 4, 5, 0, 0, 2, 1, 0, 9, 9, 8, 5, 5, 9, 8, 7, 1, 2, 0}
var gr9 = [60]int{5, 2, 0, 8, 8, 4, 4, 8, 1, 9, 4, 7, 6, 4, 4, 5, 6, 0, 6, 2, 8, 7, 6, 0, 3, 7, 6, 9, 4, 6, 2, 2, 2, 7, 9, 5, 7, 2, 4, 2, 6, 7, 5, 7, 4, 5, 1, 1, 2, 9, 7, 8, 1, 2, 4, 5, 6, 3, 5, 9}
var gr10 = [60]int{4, 5, 7, 9, 3, 4, 1, 9, 3, 1, 4, 3, 2, 6, 0, 4, 3, 3, 6, 3, 2, 6, 9, 0, 8, 2, 5, 6, 4, 5, 6, 7, 6, 2, 0, 6, 4, 3, 2, 3, 5, 1, 4, 4, 1, 7, 5, 3, 4, 3, 5, 5, 3, 6, 7, 5, 0, 3, 8, 7}
var gr11 = [60]int{3, 3, 0, 9, 0, 1, 6, 7, 5, 6, 7, 0, 3, 6, 9, 3, 5, 9, 8, 3, 6, 8, 6, 7, 2, 3, 5, 1, 5, 7, 6, 9, 6, 1, 9, 0, 5, 7, 1, 3, 1, 3, 8, 7, 6, 8, 8, 9, 9, 2, 3, 2, 1, 8, 3, 7, 2, 5, 6, 2}
var gr12 = [60]int{8, 6, 3, 9, 9, 5, 8, 9, 1, 9, 9, 5, 7, 6, 0, 3, 8, 4, 7, 3, 8, 7, 0, 7, 8, 4, 8, 9, 3, 8, 5, 3, 7, 8, 8, 3, 6, 8, 6, 6, 3, 8, 7, 5, 5, 9, 3, 9, 7, 2, 4, 8, 0, 7, 6, 2, 4, 8, 9, 2}
var gr13 = [60]int{2, 1, 6, 8, 4, 4, 4, 6, 2, 8, 9, 0, 9, 8, 3, 7, 2, 8, 4, 2, 4, 8, 5, 4, 7, 1, 7, 9, 1, 0, 9, 9, 0, 1, 2, 0, 9, 4, 5, 9, 6, 7, 7, 2, 8, 2, 6, 0, 1, 0, 1, 2, 8, 4, 7, 7, 8, 9, 1, 2}
var gr14 = [60]int{9, 9, 1, 6, 1, 5, 8, 0, 2, 1, 0, 6, 4, 2, 9, 0, 5, 9, 4, 9, 4, 9, 0, 4, 7, 2, 7, 8, 3, 5, 6, 5, 7, 4, 0, 4, 7, 0, 3, 0, 6, 6, 4, 6, 7, 3, 4, 8, 1, 5, 8, 2, 6, 7, 1, 4, 2, 5, 7, 6}
var gr15 = [60]int{5, 4, 7, 5, 7, 0, 6, 6, 5, 1, 2, 9, 6, 6, 7, 1, 4, 8, 1, 4, 9, 7, 9, 8, 2, 9, 6, 4, 2, 6, 2, 8, 7, 5, 4, 7, 0, 1, 2, 7, 5, 6, 9, 9, 1, 5, 2, 6, 0, 4, 0, 5, 0, 0, 1, 2, 1, 3, 5, 9}
var gr16 = [60]int{8, 8, 6, 6, 8, 7, 2, 5, 3, 0, 2, 4, 0, 4, 3, 4, 2, 4, 6, 0, 5, 0, 8, 2, 5, 7, 3, 4, 4, 4, 5, 2, 5, 3, 7, 2, 3, 9, 2, 6, 5, 3, 6, 0, 9, 7, 2, 6, 0, 4, 9, 2, 6, 7, 6, 3, 4, 5, 2, 3}
var gr17 = [60]int{9, 1, 0, 1, 0, 9, 6, 8, 4, 0, 0, 9, 8, 7, 5, 3, 2, 5, 6, 1, 0, 8, 0, 6, 0, 3, 8, 1, 0, 8, 5, 5, 5, 5, 7, 5, 7, 0, 8, 2, 0, 5, 7, 2, 5, 1, 5, 3, 8, 7, 4, 4, 2, 9, 9, 2, 3, 4, 6, 7}
var gr18 = [60]int{3, 6, 7, 6, 2, 4, 8, 9, 7, 5, 9, 8, 5, 7, 3, 5, 5, 4, 5, 7, 6, 4, 2, 0, 1, 5, 5, 9, 8, 3, 2, 3, 8, 5, 9, 4, 5, 6, 6, 2, 5, 5, 6, 7, 4, 8, 1, 1, 6, 3, 2, 1, 3, 6, 1, 3, 1, 9, 3, 1}
var gr19 = [60]int{8, 1, 3, 4, 2, 0, 8, 5, 1, 3, 8, 0, 6, 3, 7, 0, 8, 8, 9, 6, 8, 0, 6, 7, 2, 5, 8, 8, 3, 6, 5, 9, 6, 2, 5, 4, 8, 9, 6, 7, 2, 6, 0, 2, 0, 9, 7, 1, 4, 9, 3, 2, 4, 4, 3, 2, 2, 2, 3, 9}
var gr20 = [60]int{2, 9, 9, 1, 4, 8, 9, 3, 4, 7, 1, 9, 3, 0, 2, 5, 4, 6, 6, 3, 7, 8, 3, 9, 4, 3, 8, 0, 4, 0, 4, 3, 3, 0, 4, 7, 3, 5, 2, 1, 0, 9, 5, 2, 6, 5, 2, 1, 0, 8, 9, 2, 7, 3, 8, 4, 5, 4, 7, 5}
var gr21 = [60]int{9, 6, 6, 0, 7, 5, 0, 3, 6, 6, 3, 4, 2, 8, 3, 4, 4, 7, 2, 7, 8, 2, 8, 0, 6, 2, 8, 6, 6, 6, 3, 4, 7, 1, 4, 1, 9, 9, 3, 4, 7, 3, 2, 4, 4, 0, 7, 1, 2, 9, 2, 5, 4, 1, 2, 6, 4, 1, 1, 4}
var gr22 = [60]int{8, 5, 5, 9, 7, 7, 1, 7, 0, 5, 4, 7, 6, 5, 3, 9, 8, 3, 4, 5, 7, 8, 6, 6, 5, 2, 2, 7, 9, 7, 8, 5, 1, 1, 4, 5, 7, 4, 7, 1, 4, 9, 8, 4, 2, 3, 4, 7, 3, 3, 1, 0, 2, 9, 5, 2, 3, 2, 6, 9}
var gr23 = [60]int{0, 4, 1, 9, 3, 2, 3, 9, 2, 7, 8, 4, 2, 6, 4, 0, 5, 4, 7, 8, 9, 3, 8, 6, 2, 7, 7, 7, 8, 2, 4, 1, 4, 0, 5, 9, 3, 9, 5, 8, 6, 8, 8, 7, 2, 0, 4, 4, 4, 1, 8, 9, 7, 0, 5, 5, 3, 6, 7, 2}
var gr24 = [60]int{9, 9, 8, 3, 6, 1, 3, 9, 8, 1, 7, 4, 4, 3, 3, 7, 4, 5, 1, 1, 9, 4, 7, 8, 0, 1, 0, 4, 3, 4, 4, 0, 5, 9, 0, 7, 9, 5, 1, 8, 1, 2, 9, 5, 5, 7, 2, 5, 2, 1, 8, 1, 5, 8, 4, 2, 0, 3, 8, 9}
var gr25 = [60]int{7, 4, 1, 5, 3, 4, 0, 0, 9, 3, 1, 2, 4, 9, 7, 2, 6, 6, 7, 7, 5, 1, 9, 2, 1, 7, 8, 9, 1, 2, 3, 8, 6, 4, 8, 5, 3, 6, 3, 7, 2, 3, 8, 1, 0, 4, 0, 3, 5, 4, 8, 0, 0, 9, 9, 3, 0, 0, 7, 8}
var gr26 = [60]int{0, 9, 2, 4, 5, 0, 7, 6, 6, 3, 4, 2, 6, 6, 5, 3, 3, 7, 4, 1, 9, 7, 3, 4, 6, 1, 0, 8, 1, 7, 3, 2, 5, 0, 2, 7, 4, 5, 6, 7, 5, 2, 4, 8, 3, 0, 3, 2, 9, 8, 7, 0, 9, 4, 1, 1, 7, 0, 6, 4}
var gr27 = [60]int{5, 2, 1, 8, 6, 1, 9, 9, 9, 7, 0, 8, 7, 6, 2, 2, 2, 3, 5, 4, 1, 0, 8, 7, 3, 3, 6, 3, 3, 1, 4, 2, 6, 6, 2, 6, 8, 6, 8, 7, 0, 4, 0, 1, 6, 8, 6, 1, 4, 0, 8, 7, 4, 5, 2, 4, 1, 2, 6, 6}

var oldScores = []int{24, 44, 44, 45, 45, 47, 49, 51, 52, 52, 57, 58, 59, 60, 62, 66, 66, 71, 74, 75, 83, 87, 92, 100, 102, 107, 136}
var oldRounds = []int{84, 85, 94, 95, 99, 101, 105, 108, 112, 112, 117, 120, 121, 122, 123, 124, 125, 134, 141, 141, 166, 168, 172, 176, 178, 180, 190}
var oldSkips = []int{0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5}
