package main

/*
var testHolesField = Field{
	Grid: [][]bool{
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, true, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false},
	},
}*/
var EmptyGrig10x20 = Grid{
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
	{false, false, false, false, false, false, false, false, false, false},
}

var pieces = []string{I, J, L, O, S, T, Z}

var g1 = [400]string{L, J, J, Z, O, S, O, I, J, T, T, J, S, O, O, Z, S, S, T, O, O, T, J, L, O, S, S, S, T, I, O, Z, L, I, J, L, L, Z, I, T, J, I, T, L, J, S, T, J, Z, J, O, I, T, O, Z, L, L, I, J, L, O, T, S, O, O, L, T, I, S, Z, T, I, S, O, T, I, O, T, J, O, J, J, O, S, S, L, J, T, S, L, S, S, J, T, S, Z, J, T, J, O, L, O, O, T, S, J, O, I, I, S, Z, J, O, T, T, I, L, S, S, L, T, J, Z, S, J, S, T, Z, T, L, O, T, I, Z, I, S, O, L, J, T, I, T, J, J, O, Z, J, S, O, J, T, J, Z, T, Z, T, I, S, T, L, S, I, J, L, J, O, O, I, I, Z, Z, J, J, L, O, L, O, T, T, Z, J, S, O, S, Z, I, J, O, O, S, T, I, L, Z, S, J, J, I, T, S, L, Z, Z, J, T, Z, T, L, Z, O, L, S, O, I, L, J, T, I, S, S, S, Z, J, L, Z, Z, O, J, Z, I, J, O, L, T, I, S, O, S, O, I, L, L, S, T, Z, T, S, T, S, J, I, S, I, T, J, O, J, O, T, J, J, J, J, S, I, O, I, O, I, S, Z, Z, S, O, J, T, T, T, Z, S, S, J, O, L, L, I, T, S, J, L, I, T, Z, Z, T, J, I, O, T, I, S, S, T, O, S, L, Z, S, T, S, J, T, J, S, Z, O, S, L, T, L, J, Z, J, I, T, I, O, O, O, J, Z, J, O, O, T, T, S, T, L, J, I, J, J, I, S, O, O, I, Z, T, S, L, Z, O, T, S, L, J, L, T, S, T, I, Z, I, L, J, T, S, L, S, L, T, O, T, O, I, Z, S, J, Z, T, O, T, Z, L, J, L, I, O, J, L, T, O, I, O, L, O, J, S}
var g2 = [400]string{Z, J, I, T, I, T, Z, O, S, Z, S, Z, S, O, O, O, S, T, O, Z, L, T, J, J, Z, L, S, T, I, O, I, I, Z, O, I, I, I, I, T, T, I, T, O, T, Z, J, S, T, J, S, L, L, O, T, J, Z, I, T, S, Z, S, Z, O, O, I, T, I, S, T, J, O, L, O, L, J, S, L, I, L, Z, L, I, L, S, Z, Z, L, L, L, I, S, I, T, L, T, T, Z, I, L, L, J, L, T, S, L, L, S, O, O, L, J, T, T, O, J, L, O, J, O, T, J, T, I, Z, T, S, L, I, L, O, T, Z, S, Z, T, L, S, L, Z, J, J, Z, S, S, O, L, T, J, S, L, S, I, O, L, I, Z, O, J, J, I, T, I, T, Z, T, O, O, J, Z, I, T, L, I, J, I, T, O, J, O, T, J, T, S, I, Z, I, L, L, T, I, L, O, S, S, Z, L, T, I, O, S, S, T, T, L, L, J, L, Z, S, I, T, L, O, O, I, S, J, S, S, Z, J, O, T, Z, I, J, S, Z, O, T, T, O, O, L, O, J, T, J, S, T, Z, Z, J, T, S, L, L, J, S, L, S, S, Z, Z, I, J, L, S, T, I, J, T, O, T, J, J, S, J, S, T, L, I, L, Z, T, L, Z, O, J, J, T, Z, I, I, T, T, S, S, Z, Z, S, L, J, J, Z, L, T, O, S, Z, Z, S, O, Z, T, L, Z, O, L, T, Z, T, J, L, Z, I, T, I, T, L, Z, L, O, I, I, I, L, O, S, I, L, I, S, I, S, T, O, S, J, I, J, T, S, J, Z, J, L, T, O, J, J, S, L, O, J, L, T, I, O, O, L, L, Z, T, J, S, S, S, S, S, L, T, I, O, I, I, I, J, O, J, O, S, T, Z, I, O, Z, L, L, I, S, J, L, T, J, T, I, Z, T, L}
var g3 = [400]string{I, L, Z, T, T, L, J, S, L, T, T, T, J, T, L, I, T, T, O, T, O, S, S, T, Z, L, S, I, L, I, S, J, I, S, I, L, L, L, L, J, Z, L, T, T, L, I, L, T, Z, O, L, L, I, I, O, S, I, S, T, S, Z, O, O, J, Z, O, S, L, I, S, T, S, S, O, T, L, J, S, S, J, T, L, S, S, L, J, L, S, I, O, I, J, T, O, I, L, S, T, O, L, J, O, I, J, J, J, L, O, S, L, L, J, T, L, J, O, L, I, T, J, T, S, T, I, L, Z, L, O, J, J, O, Z, Z, J, O, O, Z, S, L, S, T, J, J, O, S, O, Z, Z, L, L, J, Z, L, I, J, J, J, O, T, I, Z, S, I, T, I, S, Z, L, J, T, S, J, T, O, T, Z, L, O, L, L, I, S, L, I, J, Z, J, J, O, Z, Z, L, J, L, J, T, L, O, O, I, I, J, Z, I, S, O, L, J, J, T, O, T, Z, Z, S, J, S, L, T, O, Z, T, Z, I, T, S, O, S, I, L, J, I, J, Z, L, O, O, Z, I, Z, I, L, J, L, I, L, S, L, J, J, O, S, I, O, L, Z, L, O, I, O, L, S, J, L, T, I, J, Z, I, T, T, O, L, J, T, L, S, I, L, L, L, L, L, O, S, Z, J, L, O, I, J, J, S, S, O, O, O, I, T, Z, O, O, S, S, I, Z, T, J, T, Z, I, I, L, I, T, S, S, Z, Z, L, Z, I, O, Z, T, O, O, O, I, T, I, O, L, S, J, I, O, Z, T, S, O, L, L, I, L, L, Z, Z, O, J, T, Z, I, I, J, J, O, J, T, L, Z, J, T, Z, J, J, J, Z, S, L, O, I, L, L, T, S, S, L, T, L, L, Z, S, Z, Z, S, S, L, L, L, O, Z, T, J, S, S, L, T, I, T}
var g4 = [400]string{I, Z, O, T, J, J, O, S, J, Z, J, J, I, J, O, I, I, I, T, O, Z, L, S, S, T, Z, T, I, S, O, Z, L, Z, J, I, T, S, J, I, Z, S, O, L, I, O, L, L, I, L, S, O, J, I, I, T, L, L, I, L, Z, L, J, I, T, T, T, Z, O, S, S, T, L, T, S, J, I, S, Z, T, O, J, S, O, S, I, Z, I, S, Z, I, T, T, I, L, L, L, Z, Z, I, T, L, J, O, J, I, L, L, L, S, Z, S, Z, T, T, O, I, J, O, J, Z, J, T, I, I, S, J, Z, T, Z, L, L, I, J, L, T, Z, I, Z, J, I, S, Z, L, I, I, Z, L, S, L, L, Z, T, L, T, T, T, O, O, O, S, T, Z, I, O, I, J, S, Z, L, O, S, S, O, J, J, J, T, T, L, T, S, T, S, Z, O, O, S, O, I, O, O, O, L, O, O, I, J, O, I, I, O, S, T, T, L, S, T, T, Z, Z, J, L, I, L, I, L, O, L, T, O, T, I, J, I, S, S, S, T, Z, T, I, T, O, S, S, S, L, S, J, T, I, Z, I, I, O, J, L, J, I, O, Z, T, I, S, I, Z, L, T, O, I, I, J, Z, Z, I, T, O, I, O, S, J, J, Z, O, O, T, O, T, I, I, O, Z, I, T, L, L, I, I, O, L, T, O, L, T, J, J, I, O, Z, Z, S, Z, Z, I, J, O, T, T, I, O, I, O, I, I, Z, T, O, L, Z, O, I, L, O, T, J, Z, S, T, O, Z, S, I, L, O, T, I, S, J, T, L, O, J, Z, Z, I, T, O, T, O, I, Z, J, O, S, L, O, S, T, J, T, L, L, L, L, J, S, J, L, S, L, O, S, I, I, S, J, L, O, Z, O, S, Z, I, S, O, Z, O, J, L, O, L, J, Z, J, J, J, T, O, L, L}
var g5 = [400]string{J, S, T, O, T, O, J, J, Z, I, I, S, O, S, O, J, O, I, L, Z, O, O, I, T, J, Z, Z, Z, Z, Z, J, L, I, J, T, T, L, O, Z, S, Z, T, T, J, I, I, Z, L, L, Z, I, J, I, T, J, L, Z, S, L, L, I, J, I, I, Z, S, T, J, T, Z, Z, Z, I, I, S, S, J, L, S, O, T, I, L, I, L, I, O, I, S, T, O, O, I, I, J, L, J, I, J, I, L, T, Z, T, T, Z, I, L, J, L, L, Z, T, T, Z, S, T, L, S, L, O, J, J, T, Z, S, L, L, Z, Z, J, S, T, O, T, L, Z, L, J, Z, S, S, O, J, O, L, S, O, S, L, L, I, T, T, Z, S, O, O, O, O, I, S, Z, O, I, S, T, S, I, L, S, J, L, L, L, L, O, T, O, S, Z, Z, S, Z, L, I, L, S, S, Z, Z, S, L, I, O, O, Z, O, T, L, I, L, L, O, S, S, O, T, S, J, L, O, O, L, J, S, T, L, L, I, L, J, S, Z, I, L, S, O, Z, L, S, I, O, O, I, L, T, T, T, S, T, O, J, T, Z, I, T, T, L, I, Z, J, J, I, O, S, Z, Z, J, L, T, Z, O, T, I, S, Z, I, T, L, I, T, S, O, I, I, L, L, I, T, T, J, I, I, J, J, O, I, J, I, T, I, I, L, J, O, T, O, L, O, Z, O, J, S, Z, O, L, S, J, J, T, S, O, J, J, L, T, T, T, O, O, S, Z, S, T, L, J, Z, I, L, J, I, Z, J, O, I, T, O, I, L, Z, Z, O, S, Z, O, L, J, S, L, O, S, Z, O, S, T, I, I, S, Z, Z, I, J, O, L, L, T, O, Z, O, Z, J, S, S, L, S, J, J, J, I, O, I, L, S, O, L, Z, L, Z, L, I, I, L, L, T, S, Z, L, J, I}
var g6 = [400]string{J, I, T, T, S, L, I, O, L, L, Z, J, Z, Z, Z, T, T, O, J, T, L, I, T, Z, I, Z, Z, S, O, I, Z, J, S, I, L, O, Z, I, I, S, O, J, I, J, J, T, L, L, L, Z, T, I, L, J, O, J, O, J, I, I, L, L, L, J, O, T, Z, T, I, O, Z, O, Z, J, L, J, S, T, Z, T, Z, I, Z, J, Z, I, J, I, I, I, O, O, J, L, Z, T, J, O, I, S, L, Z, S, I, O, Z, T, L, J, J, Z, O, I, T, T, T, Z, I, S, I, O, Z, I, I, T, L, I, L, O, O, J, O, S, I, L, I, S, Z, L, Z, I, J, Z, L, T, S, I, S, L, I, L, O, Z, T, T, Z, S, O, I, S, O, J, J, T, Z, L, O, T, L, S, Z, T, J, O, O, O, Z, T, J, O, O, L, Z, Z, I, S, S, Z, I, Z, S, O, S, Z, S, L, L, T, L, O, J, O, Z, O, L, S, S, J, I, I, Z, S, S, Z, Z, I, S, J, O, S, O, Z, O, T, O, O, T, I, I, S, L, O, Z, J, O, O, S, I, T, J, O, S, S, S, I, L, L, T, Z, S, I, T, S, I, T, I, Z, T, L, J, T, L, T, I, L, I, Z, I, T, L, J, J, L, S, Z, O, J, J, T, O, T, L, S, L, S, O, S, S, T, Z, O, O, I, T, L, J, I, J, T, O, L, T, L, T, O, L, J, L, J, I, O, Z, O, L, Z, O, T, L, J, I, J, J, Z, S, Z, L, J, T, Z, J, L, O, I, O, Z, I, O, O, Z, I, L, I, I, O, I, L, I, O, L, Z, T, J, J, O, Z, J, O, S, Z, J, O, L, Z, S, O, L, S, I, J, I, I, T, J, I, I, J, S, L, T, T, Z, L, Z, I, Z, L, L, L, L, Z, J, I, I, S, S, I, O, I, S, O}
var g7 = [400]string{I, L, L, O, O, T, I, T, O, Z, Z, T, T, T, T, O, T, S, S, J, I, J, I, J, J, J, J, T, J, L, L, I, S, Z, J, J, L, I, O, Z, T, I, J, I, S, L, J, T, O, J, J, I, I, S, S, I, O, J, J, J, O, I, O, Z, S, O, T, O, T, L, J, T, S, J, Z, T, S, Z, O, I, I, J, J, L, J, I, J, O, J, L, O, J, T, O, I, J, J, T, J, O, Z, O, L, L, T, O, O, I, L, T, T, L, T, S, O, J, S, J, S, S, Z, S, J, T, S, I, T, J, J, T, J, I, Z, L, J, T, L, S, J, J, S, I, J, Z, O, I, S, S, S, J, Z, Z, S, Z, Z, I, I, T, S, Z, I, S, O, J, Z, S, T, J, T, T, S, L, T, I, I, I, J, Z, L, Z, S, I, I, O, J, T, O, S, I, L, Z, J, S, J, S, I, L, O, O, L, O, L, O, S, L, Z, I, L, S, O, L, Z, Z, S, J, O, J, I, Z, O, Z, L, I, T, I, T, O, S, O, Z, T, I, T, L, I, J, J, Z, T, J, O, S, O, Z, J, L, L, Z, O, Z, S, J, I, I, J, Z, Z, I, L, I, Z, I, J, S, I, Z, O, L, T, O, S, S, O, Z, L, J, Z, Z, I, T, O, O, I, I, I, S, O, O, I, Z, L, L, I, J, I, I, O, Z, T, T, I, Z, L, S, S, I, O, O, L, L, Z, Z, O, T, J, L, S, I, L, I, T, J, Z, I, L, O, O, L, I, I, S, Z, S, J, I, T, O, T, I, I, O, S, Z, T, J, S, O, J, L, L, I, L, J, I, T, J, S, S, I, S, Z, I, S, J, T, T, I, I, I, I, L, O, T, S, L, S, J, J, L, S, S, J, S, O, J, T, I, O, Z, Z, J, I, I, S, Z, Z, J, S, T, O}
var g8 = [400]string{L, J, O, T, O, T, S, J, O, L, L, S, L, L, I, I, S, O, Z, Z, I, I, Z, I, O, O, Z, T, Z, J, Z, Z, O, L, Z, S, S, L, S, L, J, L, Z, L, S, O, Z, T, J, T, J, O, T, I, I, Z, O, L, T, L, Z, O, J, S, O, J, O, J, O, O, Z, S, J, S, I, Z, J, O, I, T, T, Z, L, T, S, J, Z, J, O, S, T, L, S, I, Z, Z, L, I, J, L, L, J, I, Z, T, L, S, T, L, L, T, J, Z, O, S, I, O, O, T, J, T, J, I, O, J, S, Z, Z, J, O, T, L, Z, O, O, Z, I, I, L, I, S, L, T, S, J, J, S, J, I, T, J, L, O, J, L, T, O, I, L, T, O, T, S, J, T, Z, O, S, O, I, Z, T, I, L, Z, O, J, T, I, O, Z, S, I, I, T, I, L, T, I, J, J, L, I, Z, S, S, J, J, O, S, T, J, I, S, O, T, S, S, J, J, J, T, L, L, I, Z, O, J, S, L, Z, S, L, I, Z, T, T, J, Z, I, J, O, L, O, O, L, L, T, L, L, S, O, T, I, Z, T, S, T, L, Z, T, L, I, Z, O, T, I, S, O, Z, I, I, S, J, J, L, O, J, L, T, O, J, Z, O, L, S, O, T, Z, I, J, J, S, L, O, J, I, O, S, S, S, L, O, T, S, I, I, Z, I, J, L, O, S, I, S, T, T, T, T, T, I, T, I, T, S, T, J, I, L, I, Z, L, T, O, T, O, J, L, Z, T, Z, L, T, I, T, O, Z, L, Z, T, O, J, T, O, O, L, O, S, I, I, J, Z, L, T, T, L, O, O, T, I, J, J, T, J, O, O, L, J, J, J, O, Z, Z, L, S, T, L, T, L, J, O, I, I, T, O, S, S, O, T, S, T, L, S, O, I, L, O, Z, T, S}
var g9 = [400]string{O, Z, O, T, J, O, S, S, O, O, T, L, J, J, J, I, I, I, L, S, L, S, Z, S, T, J, J, I, O, J, S, J, L, I, I, Z, I, L, J, S, T, Z, S, O, Z, S, I, J, L, S, S, Z, T, O, T, J, L, J, T, T, O, J, S, S, Z, T, S, I, L, Z, T, Z, T, I, S, J, L, I, O, O, S, L, Z, I, O, T, S, O, O, J, I, L, Z, J, J, T, O, T, T, O, L, S, S, Z, S, I, O, T, J, Z, L, J, I, I, J, J, I, O, S, J, Z, Z, Z, T, O, L, I, I, L, J, J, T, L, J, S, S, Z, O, T, I, J, O, L, S, Z, Z, O, L, T, S, T, J, S, T, I, T, L, S, I, I, O, L, S, O, O, I, O, O, J, O, Z, T, T, Z, J, S, J, T, I, L, L, O, S, S, J, S, S, I, T, T, T, T, O, Z, L, J, J, L, I, T, O, I, T, S, L, S, I, J, I, S, S, Z, T, I, O, T, S, L, I, L, J, T, I, S, J, I, O, I, I, I, I, O, T, J, Z, Z, S, Z, O, J, L, T, O, T, O, T, T, S, O, L, I, L, T, J, S, T, J, Z, L, T, T, O, O, I, T, Z, O, I, I, T, J, T, Z, T, J, T, J, I, L, S, T, I, I, O, L, S, J, O, S, I, Z, O, O, J, O, Z, L, S, L, S, Z, Z, Z, O, S, Z, J, I, T, Z, Z, L, O, S, J, Z, T, S, T, Z, J, J, T, Z, J, I, O, Z, T, O, S, T, S, Z, J, T, T, S, S, Z, L, T, I, I, I, J, T, T, S, L, Z, O, O, J, T, L, T, O, L, T, Z, Z, S, J, Z, I, J, T, Z, O, I, J, I, T, Z, S, J, I, Z, Z, J, T, I, T, Z, L, S, T, J, J, S, T, T, J, O, J, S, S, S, J}
var g10 = [400]string{J, S, O, T, L, J, O, I, S, S, S, O, L, L, S, T, T, S, J, J, J, O, I, T, O, I, T, S, J, Z, L, J, T, S, T, Z, J, Z, O, J, S, I, S, T, S, S, I, Z, O, I, T, L, S, Z, Z, I, L, T, J, I, I, J, L, Z, J, S, O, T, J, Z, J, T, O, Z, T, O, L, I, O, Z, I, J, L, Z, O, J, J, Z, T, T, T, L, S, L, Z, L, I, T, O, S, I, O, L, J, L, I, I, Z, O, L, T, T, O, I, Z, Z, I, L, T, L, Z, T, S, I, O, Z, J, J, O, S, I, Z, I, T, Z, O, T, S, T, S, S, O, O, J, S, O, J, O, Z, T, Z, T, Z, I, S, Z, S, O, S, J, L, Z, O, J, T, I, O, O, S, I, Z, T, L, Z, S, Z, L, T, J, S, T, L, J, O, Z, Z, J, S, S, J, L, T, J, I, I, S, S, L, L, I, O, I, S, O, Z, I, O, Z, Z, T, J, J, S, Z, L, S, L, Z, J, Z, L, I, T, I, S, J, S, O, T, J, I, L, I, T, J, Z, J, O, O, J, L, Z, Z, J, I, I, T, S, T, I, O, T, Z, I, J, S, O, I, T, O, I, Z, I, Z, O, S, S, J, L, Z, Z, L, T, L, L, J, T, S, J, L, I, I, I, Z, L, O, L, J, O, O, I, L, I, T, O, I, Z, L, I, I, O, O, J, I, J, Z, S, S, S, I, T, T, S, L, Z, J, I, J, L, I, Z, O, L, I, O, J, O, O, J, I, I, I, S, I, L, S, J, O, J, J, T, J, J, I, J, J, L, Z, J, L, S, S, L, S, L, L, L, L, S, L, T, J, T, J, T, T, J, Z, S, S, L, T, Z, Z, T, L, J, O, L, L, L, O, T, J, J, Z, Z, I, L, S, O, O, Z, O, J, Z, J, T, I, I}
var g11 = [400]string{O, Z, J, J, S, I, S, J, O, T, T, S, S, I, L, J, T, S, L, J, S, Z, L, L, J, J, S, T, O, T, S, T, S, S, T, O, J, T, Z, T, O, I, Z, Z, T, S, I, S, T, L, I, O, J, T, T, O, L, O, Z, Z, Z, I, T, J, S, J, T, S, J, Z, O, O, L, J, I, O, L, Z, J, O, L, I, J, L, L, L, S, O, O, I, Z, O, J, T, J, T, J, Z, Z, O, L, L, I, O, T, S, J, I, O, I, L, I, J, T, S, S, O, J, I, L, J, I, Z, I, S, Z, O, J, O, L, O, O, S, J, T, S, O, Z, J, T, L, Z, T, O, L, J, S, S, L, I, Z, S, T, I, I, I, I, J, S, S, Z, I, J, T, Z, L, L, O, L, L, O, J, T, S, Z, Z, Z, T, O, S, J, I, L, I, O, S, S, T, O, L, L, S, J, T, L, S, S, O, O, J, I, T, L, I, Z, I, J, T, L, T, L, S, T, L, I, Z, I, L, J, Z, L, J, J, S, J, Z, T, T, S, I, O, S, S, Z, S, T, J, S, I, T, T, J, L, I, I, O, J, J, I, S, S, O, T, Z, Z, S, L, Z, I, O, Z, L, T, I, J, Z, T, Z, I, T, T, O, O, Z, I, S, J, O, T, Z, I, T, Z, S, L, J, J, J, O, L, O, Z, O, I, L, L, J, T, L, J, S, J, J, O, T, Z, Z, Z, O, T, O, O, Z, T, J, L, S, S, L, L, Z, S, I, O, O, J, Z, Z, Z, I, S, T, T, Z, I, I, O, L, J, L, L, L, L, O, O, J, S, T, J, L, O, L, I, S, L, O, J, O, I, L, T, L, S, J, J, Z, L, T, I, O, I, I, O, Z, L, J, Z, S, S, O, T, Z, S, T, T, J, S, Z, L, O, O, I, S, S, I, T, J, Z, Z, Z}
var g12 = [400]string{Z, I, I, O, T, O, O, O, O, L, S, L, O, Z, I, S, S, I, L, J, O, L, T, Z, I, L, S, Z, T, T, T, S, Z, I, T, S, O, O, J, Z, T, Z, I, O, O, Z, Z, O, J, Z, T, J, Z, T, T, O, T, S, L, O, S, L, I, O, J, L, L, T, T, Z, Z, O, J, L, S, Z, S, J, I, J, Z, I, S, L, L, O, O, L, O, J, O, I, J, I, S, J, L, L, S, Z, J, O, S, I, L, S, Z, I, Z, T, O, Z, Z, I, O, Z, J, O, Z, J, J, T, O, Z, J, T, Z, O, O, L, O, L, I, J, T, T, L, Z, I, O, T, O, I, I, S, J, O, O, L, S, L, Z, S, T, J, L, J, I, J, I, Z, L, I, Z, Z, O, L, L, J, S, Z, T, I, O, T, Z, T, I, J, T, S, Z, O, I, J, O, I, J, T, J, Z, T, I, J, L, J, J, Z, O, O, Z, Z, I, L, J, S, I, O, O, I, S, T, O, O, T, S, Z, S, T, Z, S, I, S, T, L, I, T, T, L, O, O, O, I, I, O, Z, I, Z, L, L, J, O, I, J, L, Z, Z, T, J, T, L, I, T, Z, S, I, J, I, O, I, I, J, L, J, T, O, I, O, Z, Z, Z, S, J, I, Z, J, J, J, Z, Z, L, Z, J, T, I, T, L, S, Z, I, J, S, J, T, L, J, Z, L, L, T, Z, I, Z, O, J, T, S, Z, O, O, L, O, I, S, S, O, Z, I, O, I, J, I, J, L, T, O, J, O, O, O, O, O, O, I, S, S, T, J, J, L, O, O, I, T, Z, Z, I, O, L, T, J, O, T, J, S, L, L, Z, L, S, S, J, Z, Z, J, L, J, S, S, O, S, J, J, S, T, O, L, L, Z, L, S, O, O, J, J, S, S, O, S, Z, Z, J, O, S, S, O, I, Z, T, Z}
var g13 = [400]string{O, J, J, J, J, I, J, O, I, O, O, S, Z, O, I, Z, L, I, O, S, J, T, O, J, T, Z, O, Z, Z, T, I, L, Z, L, L, Z, O, T, L, J, S, T, I, S, T, I, O, S, O, J, L, Z, L, O, J, J, L, I, O, S, S, O, J, S, S, O, O, J, S, Z, Z, L, L, L, T, S, J, Z, I, T, L, O, I, Z, Z, Z, Z, T, I, I, Z, O, Z, S, T, S, O, J, S, T, I, L, O, J, O, O, T, J, S, L, J, S, I, L, I, Z, L, T, S, T, O, Z, Z, J, J, I, J, O, S, O, J, J, S, Z, O, Z, I, Z, I, J, J, O, S, T, O, L, S, J, T, J, O, T, S, T, O, I, J, T, Z, Z, Z, T, Z, S, J, J, I, O, T, L, Z, J, L, I, I, L, S, O, Z, O, J, O, Z, J, I, O, S, T, T, T, I, S, I, Z, L, I, L, Z, I, L, J, O, Z, Z, J, I, I, T, J, L, O, Z, T, Z, I, I, O, T, L, T, I, J, S, J, L, S, O, O, J, J, Z, O, T, S, O, I, T, J, J, T, L, Z, S, Z, T, S, J, S, Z, L, T, O, S, I, I, S, Z, T, S, Z, T, I, T, S, I, T, T, L, Z, J, Z, J, O, J, O, J, L, J, I, O, J, O, S, J, J, S, T, T, Z, S, Z, T, I, J, L, J, I, J, Z, L, O, O, T, Z, Z, I, S, I, L, O, L, S, I, S, Z, O, S, O, J, T, Z, T, S, I, J, I, Z, L, I, I, L, Z, T, O, Z, L, S, I, Z, T, Z, J, I, Z, J, T, T, J, O, I, S, I, T, S, J, T, I, O, S, J, O, O, S, I, Z, S, L, I, O, L, T, Z, O, L, T, L, Z, Z, S, I, L, I, S, I, T, O, I, T, J, T, I, S, S, J, L, O, O, T, Z, O}
var g14 = [400]string{T, S, O, J, I, O, T, Z, L, I, J, O, L, T, I, L, J, T, J, L, J, T, S, L, L, S, L, J, J, L, S, L, J, O, J, Z, I, Z, S, Z, L, J, I, L, T, O, J, O, J, T, T, S, Z, J, T, I, O, L, O, T, Z, L, I, S, S, J, L, Z, O, Z, J, Z, L, J, L, S, S, J, T, L, S, I, L, T, I, S, Z, O, S, J, Z, Z, Z, L, Z, T, I, L, I, T, S, J, O, T, O, J, I, J, I, I, J, O, S, L, J, L, L, T, I, S, S, Z, S, L, T, L, J, J, T, Z, O, S, S, O, S, L, L, Z, T, Z, L, S, O, O, S, T, J, O, J, I, J, I, L, L, J, L, J, S, Z, S, O, I, O, O, Z, I, L, O, O, I, J, Z, O, I, I, O, T, S, T, S, Z, J, J, L, S, O, T, I, I, T, T, L, Z, L, L, T, J, L, O, J, T, J, I, L, S, L, J, O, L, I, L, L, I, Z, S, S, L, L, Z, L, Z, L, T, I, J, Z, J, I, O, T, T, J, Z, L, O, Z, I, S, Z, I, S, L, O, L, Z, S, Z, J, L, I, L, S, L, T, Z, O, Z, O, Z, J, Z, T, J, I, Z, J, L, J, T, S, Z, O, L, T, T, T, I, L, L, S, I, J, T, L, J, I, J, I, L, Z, I, L, L, Z, Z, S, J, O, J, T, L, S, I, S, J, O, Z, J, J, O, O, J, L, O, T, L, J, I, O, O, T, I, T, O, Z, S, Z, J, L, L, J, S, S, T, T, S, I, J, Z, L, J, J, T, S, J, S, O, T, I, J, S, S, S, Z, I, I, O, S, Z, O, Z, L, Z, O, O, S, L, Z, O, I, S, J, S, I, S, L, I, Z, L, O, S, J, L, O, T, Z, J, J, I, S, T, J, J, T, I, J, I, T, S, S}
var g15 = [400]string{J, T, I, Z, Z, J, S, L, S, S, S, O, J, I, Z, J, J, J, S, O, Z, T, S, I, Z, T, I, S, J, S, J, O, J, O, I, L, I, S, I, J, O, O, Z, L, O, O, I, S, T, I, O, Z, T, S, L, J, T, I, I, T, S, J, T, L, J, I, O, J, Z, L, J, S, J, T, T, O, S, O, Z, L, S, T, S, O, O, T, L, L, T, Z, Z, L, T, S, O, S, I, T, Z, O, T, L, T, O, O, J, S, S, Z, I, O, Z, I, L, S, O, O, S, Z, T, T, I, I, Z, S, L, I, S, I, Z, O, S, S, I, L, T, S, O, S, J, I, T, I, O, T, I, J, I, I, O, L, S, S, I, S, L, S, J, S, Z, J, J, Z, L, T, S, O, S, I, O, O, J, O, L, O, S, J, L, J, T, I, S, S, T, S, O, T, J, T, Z, J, S, S, Z, Z, J, J, Z, J, T, Z, J, I, Z, Z, S, J, Z, Z, Z, O, S, S, O, Z, I, I, S, O, J, T, T, O, L, L, T, L, I, I, T, T, L, J, O, O, S, L, I, Z, I, S, O, O, J, O, J, I, T, S, T, T, O, T, O, T, T, T, S, O, I, I, O, I, T, I, L, S, T, T, Z, S, T, T, J, J, T, I, Z, L, O, I, I, J, Z, J, J, O, J, I, O, I, T, S, I, O, J, I, L, L, L, O, J, T, L, I, T, I, Z, T, L, J, T, J, O, I, I, L, L, S, T, O, L, I, Z, O, S, L, O, S, Z, S, J, Z, I, J, I, T, L, Z, T, Z, O, I, L, L, J, T, I, S, O, T, S, I, S, J, O, I, O, O, S, O, Z, I, S, L, T, T, I, I, S, O, O, J, J, J, O, O, T, I, S, L, J, I, I, O, Z, S, S, T, Z, Z, Z, Z, Z, S, I, L, J, J, O}
var g16 = [400]string{Z, S, L, I, S, O, L, L, L, Z, Z, S, Z, I, O, S, L, O, S, J, J, S, I, T, O, O, Z, I, S, O, O, L, S, S, Z, S, L, I, T, J, Z, J, L, I, Z, Z, I, I, T, O, J, J, Z, O, Z, L, J, O, I, I, J, I, J, I, S, I, Z, I, L, S, S, S, I, L, I, J, J, T, S, O, O, O, O, T, I, O, I, L, L, I, J, T, Z, O, T, S, I, J, I, T, J, S, I, T, O, J, J, O, T, T, S, Z, L, J, J, O, T, L, T, O, J, O, O, O, O, Z, T, S, T, L, L, J, O, O, T, O, L, Z, J, S, Z, J, I, Z, S, Z, O, T, L, S, J, S, O, L, Z, O, O, S, I, T, L, T, Z, I, T, J, L, Z, Z, S, J, I, Z, O, O, I, O, T, I, O, O, J, T, I, I, S, T, O, T, J, S, L, Z, O, J, Z, T, J, O, Z, I, T, T, L, S, L, J, L, S, I, O, O, T, J, S, O, S, S, O, S, I, I, O, I, I, J, J, S, Z, S, Z, Z, O, S, L, J, T, O, O, L, S, O, Z, O, J, S, I, I, Z, Z, Z, T, J, J, J, L, I, T, T, S, Z, T, T, L, O, S, Z, O, L, L, L, I, O, T, S, O, J, J, S, L, I, I, I, L, Z, O, L, S, I, Z, I, T, L, J, Z, Z, Z, Z, S, Z, S, O, L, Z, J, I, Z, O, Z, I, T, I, I, S, T, I, S, O, T, J, O, L, J, I, S, T, Z, L, Z, T, I, I, T, L, O, J, T, O, S, I, J, I, T, S, L, S, L, Z, L, S, O, Z, S, J, J, O, T, J, T, I, I, L, O, S, Z, O, J, I, J, J, I, I, S, I, S, L, J, Z, T, L, S, S, Z, L, S, S, L, J, T, L, O, J, Z, L, I, O, T, O, L, T}
var g17 = [400]string{L, L, L, Z, I, T, T, I, T, I, S, L, J, J, I, Z, S, L, T, Z, I, O, T, T, L, T, Z, O, L, J, S, O, T, T, O, O, Z, J, O, O, Z, L, O, L, L, S, T, S, S, O, I, L, Z, T, Z, T, Z, L, S, Z, L, O, S, I, Z, I, O, O, S, I, L, T, L, Z, Z, S, L, I, J, I, L, T, J, Z, Z, Z, Z, I, T, T, J, S, T, O, J, O, T, I, O, J, S, L, O, O, S, Z, T, S, T, L, J, J, O, O, L, J, I, T, Z, I, L, J, L, T, S, T, O, L, J, Z, T, T, I, I, S, J, L, J, T, J, T, T, I, L, L, I, S, I, Z, T, S, I, J, T, T, O, L, Z, T, L, O, I, T, J, Z, J, Z, T, J, O, L, J, Z, Z, J, L, O, O, J, Z, J, T, I, I, Z, Z, O, L, Z, L, Z, Z, L, T, Z, T, S, I, Z, Z, S, J, L, T, J, O, T, T, I, S, I, L, J, T, Z, J, Z, J, Z, Z, S, T, L, I, I, O, O, L, L, O, T, L, J, L, T, J, Z, Z, J, O, T, I, Z, J, I, Z, O, Z, J, Z, T, Z, I, T, T, O, O, I, T, J, J, Z, I, T, L, S, L, T, I, J, L, I, T, L, J, Z, T, T, O, I, J, O, Z, I, S, J, S, I, T, S, O, I, L, Z, L, Z, O, T, S, J, L, T, Z, O, L, S, L, T, L, O, S, T, L, I, J, Z, Z, S, Z, L, S, Z, J, O, S, O, I, J, Z, T, O, Z, Z, O, O, S, L, L, S, J, O, I, O, Z, Z, T, L, Z, T, O, L, T, I, L, O, O, I, L, J, L, I, O, T, J, Z, T, L, T, I, L, Z, I, I, T, S, T, T, O, J, Z, Z, J, I, Z, O, L, S, S, Z, I, L, Z, Z, Z, T, T, Z, O, J, T}
var g18 = [400]string{S, Z, O, J, L, I, T, Z, Z, Z, I, T, J, Z, L, Z, L, I, S, L, Z, S, Z, S, S, S, S, O, L, Z, Z, Z, I, I, J, L, O, L, L, S, L, Z, S, T, I, T, S, I, J, Z, O, S, Z, S, J, T, T, L, T, O, Z, J, I, J, T, I, O, Z, T, L, L, S, O, T, T, J, T, T, Z, S, T, J, S, I, O, L, O, T, I, O, J, L, L, O, I, L, O, J, S, L, T, T, S, Z, T, L, Z, J, O, O, T, S, O, L, O, O, S, I, I, O, I, Z, S, Z, Z, L, T, T, L, O, J, O, Z, J, S, I, T, L, O, I, J, I, L, I, I, S, J, I, Z, S, L, T, I, J, J, T, Z, S, Z, J, Z, J, J, Z, J, S, S, Z, S, T, O, J, I, L, L, S, O, Z, I, T, Z, J, L, L, O, L, Z, I, J, S, Z, J, I, L, I, S, J, L, I, T, T, L, S, I, O, L, O, S, L, O, S, Z, O, S, Z, L, L, O, L, S, L, O, L, J, Z, T, J, T, Z, T, O, T, T, S, S, L, O, I, Z, Z, O, J, T, T, T, O, L, J, I, S, J, J, L, I, J, L, J, Z, I, Z, Z, T, J, S, O, I, S, T, J, S, Z, L, S, O, O, T, S, O, L, L, Z, T, J, Z, L, Z, L, J, T, Z, T, O, Z, O, T, S, J, Z, J, S, L, J, I, J, S, Z, I, S, S, J, Z, S, L, L, O, T, I, O, I, I, L, I, T, J, T, O, T, Z, L, S, Z, J, I, O, Z, J, Z, I, I, O, O, L, O, S, J, Z, L, I, J, S, J, Z, O, J, L, I, Z, O, O, J, Z, T, I, S, S, O, O, S, J, T, L, S, S, T, L, Z, J, Z, I, T, O, T, T, J, Z, J, J, I, T, J, L, Z, J, T, Z, S, Z, S, J, S}
var g19 = [400]string{T, I, I, J, J, O, L, S, Z, J, Z, O, L, O, T, T, O, L, J, S, L, I, J, O, Z, I, S, T, J, T, Z, L, I, O, J, L, J, Z, I, L, S, L, O, S, S, T, T, Z, L, J, L, L, O, S, I, T, O, S, I, S, I, O, L, I, I, J, J, T, S, S, T, Z, J, O, T, S, S, L, I, S, L, J, Z, T, L, O, T, T, I, Z, I, L, T, Z, Z, L, O, S, T, L, J, Z, L, O, Z, T, J, T, O, Z, T, T, S, J, J, Z, T, Z, I, L, T, L, J, O, Z, J, I, Z, I, O, J, J, Z, I, T, J, J, J, L, L, S, I, I, I, T, T, S, O, I, T, T, I, Z, T, O, J, S, T, Z, L, L, Z, L, J, S, O, O, S, I, T, J, O, O, O, Z, Z, T, Z, T, S, T, J, S, O, L, L, I, S, S, S, L, L, I, Z, S, L, Z, L, T, Z, T, L, O, Z, O, Z, T, Z, I, S, O, O, J, I, T, Z, T, T, O, Z, O, O, J, Z, J, J, O, J, S, O, Z, T, I, Z, T, S, L, J, J, I, J, Z, T, I, S, T, I, S, T, O, Z, O, J, S, L, O, T, I, Z, J, Z, Z, J, S, Z, I, O, J, O, I, L, Z, O, O, J, I, O, J, J, T, Z, O, T, S, O, S, O, S, I, I, I, T, S, Z, Z, S, O, T, L, T, L, J, Z, L, I, O, T, J, O, Z, S, S, L, I, S, O, J, L, L, S, O, J, Z, T, L, S, O, T, Z, I, I, L, J, S, Z, L, J, J, I, Z, O, L, I, S, S, I, J, J, Z, S, T, J, Z, O, I, L, O, Z, T, I, J, O, T, J, S, T, Z, Z, L, O, J, I, Z, L, J, I, L, O, J, O, L, Z, O, T, I, I, T, Z, O, L, J, O, S, J, L, T, O, S, S, L}
var g20 = [400]string{J, Z, S, J, S, S, J, S, J, O, I, Z, I, Z, O, S, I, L, S, L, T, S, J, S, T, S, O, Z, Z, J, J, T, Z, S, J, T, T, Z, J, J, I, J, Z, L, L, Z, O, T, L, J, O, S, L, O, I, L, O, Z, I, L, I, L, O, L, S, J, L, Z, Z, Z, O, Z, J, T, S, I, L, L, Z, Z, Z, O, O, Z, I, O, I, O, S, S, J, Z, S, S, L, O, L, L, T, Z, O, O, O, L, I, S, L, L, I, I, L, J, O, I, L, I, O, O, I, O, O, L, S, J, J, J, O, J, O, I, T, S, T, O, I, T, J, T, O, Z, I, O, S, I, Z, J, O, O, J, Z, L, T, I, Z, L, L, I, O, O, T, T, S, O, L, I, J, T, I, T, O, T, I, J, L, Z, S, O, T, L, S, I, L, S, J, L, L, S, J, L, I, Z, S, T, L, Z, L, J, O, Z, Z, J, S, L, S, Z, L, O, J, O, T, O, S, T, I, T, T, J, L, J, T, O, J, Z, J, O, J, L, O, I, J, O, I, S, Z, S, L, O, I, Z, Z, S, T, Z, T, O, J, O, T, Z, L, J, L, S, I, L, O, I, O, O, I, O, T, Z, Z, I, T, S, J, T, S, L, Z, O, J, T, J, J, I, T, J, I, J, T, S, O, Z, I, I, I, T, I, T, L, J, Z, I, O, S, T, Z, J, L, L, S, Z, T, S, S, S, J, O, I, J, S, J, J, S, S, L, Z, L, J, O, T, Z, T, L, L, S, S, L, L, J, S, T, O, J, S, J, I, L, J, Z, T, Z, S, T, O, Z, O, J, Z, Z, I, O, S, T, Z, L, T, J, S, S, I, Z, L, S, T, O, L, O, Z, O, L, I, T, O, J, I, L, L, Z, I, T, L, I, O, O, J, Z, T, O, O, S, I, T, I, S, Z, Z}
var g21 = [400]string{S, I, S, S, T, Z, Z, T, J, J, L, L, I, S, L, J, I, I, O, S, I, J, J, S, Z, O, J, S, O, J, I, Z, O, Z, T, O, O, S, O, L, O, T, L, J, I, T, Z, O, S, S, J, O, I, L, T, S, J, Z, Z, L, I, Z, S, I, L, L, Z, I, J, J, I, J, I, J, I, L, L, Z, O, S, Z, I, Z, Z, T, Z, Z, O, L, S, O, J, O, J, Z, Z, S, S, L, O, Z, J, I, J, T, O, L, O, L, O, I, O, O, S, S, I, T, T, I, O, Z, S, S, L, Z, S, L, L, S, J, Z, J, L, I, L, O, T, I, J, I, Z, S, L, Z, J, O, J, S, T, I, Z, O, Z, Z, L, O, J, Z, I, J, T, L, O, Z, L, T, T, S, I, T, O, I, J, Z, Z, I, S, I, J, L, S, Z, Z, J, Z, T, S, I, O, J, O, L, J, Z, J, Z, T, Z, T, O, O, T, J, T, Z, O, T, I, T, L, I, I, O, T, L, Z, T, O, J, T, S, O, S, Z, O, J, I, L, O, I, T, S, L, S, L, J, L, L, L, S, I, J, I, Z, Z, T, J, J, J, J, L, Z, T, T, O, J, Z, J, L, L, Z, T, J, O, J, J, L, O, Z, Z, Z, J, J, S, I, J, O, Z, J, S, T, J, T, I, J, T, S, L, J, Z, L, O, S, J, L, L, O, J, T, T, J, J, L, I, O, J, S, T, T, T, L, Z, T, T, Z, I, Z, T, J, I, J, Z, O, Z, I, Z, L, O, S, Z, S, I, J, Z, T, S, L, Z, T, I, I, O, J, J, I, S, O, I, O, J, T, I, L, L, O, Z, Z, S, Z, J, O, I, T, S, O, Z, T, S, I, I, L, J, J, O, L, O, O, I, I, S, J, S, L, O, Z, S, T, I, L, L, L, J, O, O, J, S, Z, S, O, J}
var g22 = [400]string{S, L, I, O, Z, Z, I, S, J, I, L, S, L, S, J, S, J, J, J, Z, L, T, I, S, T, I, S, T, J, J, S, L, S, Z, L, O, O, I, O, T, O, L, S, O, T, L, T, S, J, I, Z, L, S, T, J, T, L, I, O, I, I, I, T, L, O, J, T, I, I, T, L, J, J, I, I, J, L, Z, S, O, J, Z, Z, I, J, T, L, I, Z, S, S, Z, Z, Z, S, J, I, S, L, Z, J, L, O, I, L, S, L, T, Z, I, L, I, J, O, S, S, S, L, L, I, Z, L, Z, J, Z, L, O, Z, O, O, S, S, Z, Z, Z, L, T, T, S, T, Z, O, J, S, O, L, O, L, L, L, I, I, S, O, Z, S, J, L, T, I, Z, S, O, I, O, J, T, S, T, S, J, O, T, T, Z, L, T, T, T, T, O, Z, O, O, O, L, O, S, Z, I, S, L, O, L, S, I, I, T, I, J, S, S, Z, L, I, L, J, O, S, T, I, J, O, O, Z, Z, Z, S, I, O, J, S, I, I, T, S, J, S, S, L, Z, T, S, L, L, Z, Z, I, I, J, S, L, I, T, L, O, Z, O, S, O, I, S, J, T, Z, O, Z, I, S, T, T, S, Z, Z, I, T, I, O, L, J, Z, L, Z, S, S, I, O, Z, J, L, L, S, I, O, Z, J, Z, J, J, J, I, O, Z, S, L, Z, T, S, Z, L, S, O, I, Z, T, O, Z, L, Z, T, L, Z, J, O, O, J, J, Z, J, O, I, T, J, O, T, T, S, Z, L, Z, L, S, Z, Z, Z, J, Z, I, L, J, T, T, T, J, I, Z, S, J, J, L, Z, L, T, J, I, S, J, J, L, I, T, S, S, I, J, J, O, S, S, S, J, L, I, L, T, T, I, O, T, I, L, T, L, S, S, J, T, O, L, J, O, Z, S, L, T, Z, Z, Z, L, J}
var g23 = [400]string{Z, Z, L, I, S, I, S, T, T, O, T, L, J, S, O, S, T, T, L, S, Z, T, I, J, O, J, T, I, S, O, S, Z, L, L, Z, Z, I, J, I, J, Z, L, I, T, T, J, L, Z, Z, S, S, Z, O, O, S, I, Z, I, T, I, T, L, S, O, T, T, O, I, O, T, I, L, I, L, J, I, S, S, S, O, L, J, S, Z, J, S, I, S, O, O, T, S, L, L, T, L, I, I, S, S, Z, Z, L, L, S, T, L, O, J, S, S, L, J, O, J, J, S, L, I, O, O, L, J, O, J, I, I, O, T, L, O, I, L, O, S, I, T, T, T, O, Z, L, L, I, I, Z, I, T, T, I, I, Z, T, J, T, Z, T, J, T, S, I, O, Z, S, T, L, I, L, J, O, I, Z, L, S, O, S, Z, S, O, Z, S, L, L, J, I, O, Z, O, L, J, J, L, O, Z, S, Z, Z, L, O, L, I, I, L, T, J, J, S, T, L, T, Z, S, T, T, L, J, T, L, L, J, Z, I, Z, J, J, O, J, Z, J, J, O, Z, L, T, I, T, I, Z, S, T, L, T, S, I, O, I, O, T, L, L, O, J, Z, I, T, Z, S, L, T, J, S, L, S, I, O, S, I, S, S, Z, I, T, O, Z, T, O, L, O, S, I, T, I, L, Z, Z, O, L, J, L, S, Z, J, Z, O, I, L, L, T, J, L, T, Z, O, O, Z, O, S, O, S, I, T, O, S, O, T, S, O, Z, S, L, L, S, J, L, O, J, I, T, T, I, L, L, T, L, O, Z, O, S, O, S, S, J, L, J, T, J, Z, Z, L, L, T, L, T, S, L, T, S, T, S, J, S, T, O, J, S, S, S, O, S, L, O, T, O, Z, Z, S, S, T, I, I, T, T, Z, J, L, J, S, O, J, S, T, J, I, S, J, S, T, J, O, J}
var g24 = [400]string{S, S, T, I, L, T, T, L, O, Z, L, S, S, O, T, L, L, Z, O, I, T, T, T, Z, S, L, Z, Z, L, O, O, T, S, L, O, O, J, J, L, J, I, S, O, O, Z, I, T, Z, Z, J, Z, J, O, I, Z, J, I, O, T, I, J, O, I, O, I, L, S, L, O, Z, L, O, I, O, J, S, J, I, O, S, Z, S, O, S, Z, I, O, L, L, T, Z, L, O, I, Z, S, Z, O, I, T, Z, J, O, O, L, L, L, T, J, O, T, Z, O, T, J, J, O, L, Z, I, S, S, O, L, O, T, Z, T, T, J, S, T, I, I, J, T, J, Z, O, J, T, O, T, I, O, S, S, T, L, S, S, T, L, O, L, T, L, Z, Z, L, L, O, O, L, Z, J, Z, L, J, I, I, T, Z, T, S, L, Z, S, S, I, L, L, O, L, J, J, T, T, S, L, J, Z, Z, Z, T, I, J, O, Z, Z, T, J, J, O, O, T, I, T, S, I, Z, T, Z, J, Z, T, Z, T, Z, Z, S, L, O, I, O, S, T, J, L, I, Z, T, O, I, Z, T, J, I, L, J, T, S, L, L, I, Z, J, I, I, I, L, S, Z, J, O, L, T, O, O, S, I, J, T, T, S, J, T, Z, L, T, I, O, L, I, I, S, L, Z, J, J, S, I, I, L, O, I, L, O, T, L, O, S, S, I, O, O, T, O, I, Z, Z, I, Z, Z, L, J, Z, J, L, T, L, Z, O, J, O, J, J, J, J, J, Z, O, O, Z, T, O, I, J, L, J, T, L, Z, S, J, Z, J, I, I, I, Z, Z, O, I, Z, T, Z, I, T, J, S, J, Z, S, O, Z, J, T, O, J, J, S, Z, I, S, S, T, T, O, S, S, O, S, L, T, I, Z, S, Z, I, T, T, S, I, S, L, T, S, I, I, J, I, Z, Z, L, J, T, I, I, O}
var g25 = [400]string{S, Z, S, L, T, Z, O, Z, I, L, J, O, T, O, T, O, S, L, J, T, T, J, Z, T, T, O, J, Z, J, I, I, S, L, L, S, I, O, O, O, O, S, I, S, S, I, L, Z, S, I, T, J, L, J, Z, I, I, O, O, Z, S, T, T, L, L, L, Z, J, T, T, J, Z, S, Z, S, I, L, O, J, Z, T, O, L, J, I, S, T, T, O, Z, L, Z, I, Z, L, T, L, L, J, S, O, J, I, T, Z, I, I, I, S, Z, O, L, T, L, Z, Z, O, I, S, I, J, I, J, L, S, S, L, J, T, L, J, I, L, I, L, Z, L, T, Z, I, I, T, T, T, T, I, J, T, I, I, S, O, S, S, Z, L, O, L, T, Z, T, J, J, T, I, T, I, J, Z, L, Z, J, O, S, T, S, Z, L, Z, T, S, O, Z, Z, I, L, Z, L, I, S, T, J, Z, T, I, S, S, L, Z, T, O, J, I, L, Z, J, J, O, L, O, S, I, S, L, L, Z, Z, O, L, J, S, Z, S, J, L, S, O, J, S, J, I, L, O, T, T, L, S, Z, L, I, S, L, Z, S, Z, J, L, I, T, Z, I, Z, T, I, L, O, Z, T, L, O, O, I, S, O, I, T, S, S, O, I, J, O, I, L, Z, T, S, J, O, L, T, T, L, Z, J, L, J, T, O, L, L, I, O, T, O, L, T, J, J, Z, S, J, I, T, T, T, L, S, L, J, I, L, J, L, Z, I, O, J, I, L, I, Z, S, T, S, L, S, I, J, T, L, T, I, Z, I, Z, I, T, S, S, Z, T, I, Z, L, I, L, O, T, Z, I, L, T, Z, L, Z, S, S, Z, O, L, J, O, S, T, S, I, I, Z, S, Z, J, O, I, Z, Z, J, O, S, S, S, J, J, T, S, J, S, L, S, T, I, S, O, L, O, T, O, S, L, T, T}
var g26 = [400]string{O, O, L, Z, S, Z, I, Z, S, S, O, O, O, L, I, O, T, T, J, T, O, O, I, T, J, J, Z, O, S, Z, J, T, Z, J, T, J, S, L, S, L, J, Z, O, Z, J, Z, I, T, I, S, T, J, T, O, S, L, I, L, L, J, O, I, S, T, J, O, Z, I, J, O, I, S, Z, Z, J, L, I, Z, O, T, J, O, J, T, I, Z, J, O, I, J, S, T, J, S, Z, Z, O, Z, T, J, Z, T, Z, O, Z, T, I, L, T, T, O, O, S, S, L, I, T, J, Z, I, T, I, T, I, S, I, L, T, Z, I, I, T, S, S, T, I, Z, T, T, J, S, L, I, L, S, T, J, J, T, I, I, L, I, O, S, L, L, I, Z, T, Z, O, S, I, J, O, Z, J, L, Z, Z, Z, L, L, Z, S, I, Z, I, O, T, T, S, L, S, O, T, S, I, I, S, O, S, O, J, J, I, Z, O, T, I, L, O, Z, O, J, L, Z, Z, O, I, J, L, S, I, I, S, L, S, Z, Z, S, L, Z, L, J, I, J, L, J, Z, J, J, I, Z, I, T, O, I, I, S, Z, S, J, L, L, Z, J, O, I, I, O, O, O, S, Z, O, S, L, I, Z, T, I, S, L, L, Z, T, J, S, T, Z, S, J, J, J, T, Z, L, S, T, I, I, L, O, S, L, S, T, I, Z, S, L, L, O, L, T, I, T, S, I, O, S, J, O, T, L, Z, T, L, I, T, I, S, Z, Z, Z, O, L, S, I, O, L, O, J, T, L, Z, Z, S, O, I, T, O, J, Z, Z, S, J, O, S, I, S, T, I, L, J, J, O, O, O, L, S, J, Z, J, S, S, T, S, I, J, J, Z, I, I, J, T, O, S, T, L, J, Z, I, J, Z, I, I, T, I, I, L, I, O, J, S, I, Z, T, S, T, J, S, T, J, T, S, T, I}

var gr1 = [60]int{8, 3, 7, 3, 6, 3, 7, 5, 4, 4, 8, 6, 6, 6, 4, 2, 3, 9, 9, 3, 0, 6, 9, 6, 7, 5, 9, 3, 1, 6, 2, 8, 9, 5, 8, 5, 8, 1, 0, 5, 7, 5, 9, 2, 1, 6, 3, 8, 1, 0, 4, 3, 5, 0, 8, 0, 1, 9, 5, 1}
var gr2 = [60]int{3, 4, 7, 3, 4, 6, 1, 3, 2, 2, 3, 7, 0, 5, 2, 9, 7, 1, 2, 4, 1, 0, 1, 3, 8, 5, 0, 6, 3, 3, 7, 5, 9, 4, 0, 7, 0, 8, 4, 0, 0, 8, 8, 3, 8, 1, 7, 7, 3, 2, 4, 1, 1, 8, 5, 8, 6, 7, 1, 9}
var gr3 = [60]int{3, 8, 2, 9, 0, 6, 9, 4, 9, 9, 9, 7, 3, 3, 9, 4, 4, 5, 7, 0, 5, 3, 0, 9, 9, 4, 3, 6, 8, 1, 0, 2, 1, 1, 1, 7, 3, 1, 9, 8, 0, 1, 4, 4, 4, 8, 0, 9, 2, 2, 7, 9, 3, 0, 0, 0, 6, 4, 1, 4}
var gr4 = [60]int{7, 2, 0, 0, 3, 6, 0, 4, 5, 9, 9, 7, 3, 4, 7, 9, 7, 5, 9, 1, 9, 6, 9, 2, 5, 4, 7, 7, 9, 4, 4, 2, 0, 7, 5, 8, 9, 1, 2, 0, 2, 6, 8, 4, 2, 8, 8, 7, 3, 1, 2, 9, 4, 7, 1, 5, 4, 2, 0, 1}
var gr5 = [60]int{1, 4, 1, 7, 6, 6, 5, 1, 7, 6, 1, 9, 8, 3, 2, 9, 2, 6, 3, 8, 2, 3, 4, 1, 0, 5, 9, 5, 8, 1, 9, 9, 4, 6, 8, 1, 0, 7, 9, 3, 5, 0, 4, 2, 5, 7, 1, 8, 8, 2, 4, 5, 6, 4, 1, 6, 2, 7, 3, 1}
var gr6 = [60]int{9, 5, 6, 7, 1, 1, 3, 5, 2, 3, 1, 3, 5, 7, 5, 8, 3, 1, 1, 3, 6, 9, 2, 0, 8, 6, 2, 1, 3, 9, 0, 9, 0, 5, 0, 3, 3, 3, 5, 5, 4, 3, 5, 9, 6, 5, 4, 3, 7, 5, 1, 4, 8, 2, 3, 9, 7, 9, 5, 3}
var gr7 = [60]int{4, 1, 0, 6, 0, 8, 1, 0, 4, 6, 9, 5, 7, 8, 5, 8, 2, 5, 0, 7, 5, 6, 8, 9, 6, 0, 7, 6, 8, 7, 8, 1, 1, 0, 7, 8, 9, 1, 2, 1, 3, 6, 8, 6, 9, 5, 9, 5, 9, 0, 5, 7, 0, 0, 8, 3, 1, 9, 6, 1}
var gr8 = [60]int{9, 7, 7, 5, 4, 1, 6, 8, 9, 2, 8, 8, 0, 5, 2, 4, 9, 2, 7, 7, 4, 3, 9, 9, 8, 8, 0, 9, 9, 7, 3, 3, 7, 6, 7, 4, 1, 3, 5, 1, 8, 9, 0, 4, 7, 1, 9, 9, 2, 8, 1, 7, 9, 1, 0, 9, 1, 2, 0, 8}
var gr9 = [60]int{2, 6, 7, 5, 9, 0, 4, 3, 7, 9, 7, 2, 6, 0, 4, 9, 7, 1, 1, 3, 4, 8, 1, 3, 0, 1, 0, 0, 6, 8, 8, 5, 5, 6, 0, 5, 0, 2, 5, 9, 3, 6, 3, 5, 6, 1, 6, 1, 8, 3, 6, 1, 2, 0, 1, 6, 9, 5, 3, 1}
var gr10 = [60]int{0, 2, 5, 0, 6, 2, 8, 9, 8, 1, 3, 5, 8, 6, 3, 6, 3, 1, 8, 0, 9, 3, 5, 9, 9, 3, 9, 8, 9, 7, 3, 1, 5, 4, 2, 4, 1, 0, 2, 0, 7, 1, 9, 4, 6, 5, 3, 2, 9, 8, 8, 7, 6, 6, 7, 0, 2, 3, 9, 9}
var gr11 = [60]int{1, 7, 3, 6, 9, 8, 6, 6, 1, 7, 3, 8, 8, 8, 7, 0, 4, 8, 3, 6, 0, 3, 5, 2, 5, 4, 4, 9, 9, 1, 8, 7, 4, 9, 7, 8, 2, 9, 2, 6, 4, 2, 9, 1, 9, 8, 1, 5, 6, 7, 2, 4, 5, 6, 9, 4, 9, 1, 3, 5}
var gr12 = [60]int{7, 7, 3, 1, 4, 7, 4, 3, 9, 3, 4, 1, 1, 1, 9, 2, 8, 8, 5, 0, 9, 0, 9, 5, 8, 6, 6, 5, 9, 1, 6, 2, 1, 1, 9, 5, 5, 2, 9, 5, 9, 1, 9, 5, 0, 6, 0, 9, 9, 0, 5, 3, 7, 8, 9, 9, 9, 5, 3, 3}
var gr13 = [60]int{0, 2, 2, 1, 3, 4, 7, 5, 6, 2, 6, 2, 6, 4, 5, 6, 0, 9, 7, 3, 8, 6, 3, 9, 1, 2, 0, 7, 8, 6, 7, 4, 0, 3, 2, 3, 8, 5, 0, 6, 8, 6, 2, 0, 4, 3, 1, 2, 0, 7, 1, 0, 3, 2, 1, 3, 8, 9, 1, 5}
var gr14 = [60]int{6, 3, 0, 0, 6, 2, 4, 8, 1, 4, 1, 0, 1, 2, 4, 0, 5, 7, 5, 1, 2, 4, 4, 0, 9, 6, 5, 1, 8, 7, 4, 4, 5, 9, 7, 6, 1, 8, 6, 2, 3, 7, 1, 5, 5, 8, 5, 4, 5, 0, 3, 7, 5, 3, 7, 7, 1, 9, 0, 0}
var gr15 = [60]int{1, 9, 2, 5, 1, 7, 3, 2, 0, 8, 2, 6, 7, 7, 4, 3, 2, 9, 7, 8, 4, 3, 2, 9, 9, 6, 8, 4, 4, 0, 1, 0, 5, 8, 6, 9, 1, 7, 8, 4, 2, 5, 0, 8, 9, 3, 7, 8, 3, 0, 3, 3, 9, 1, 9, 0, 8, 4, 9, 9}
var gr16 = [60]int{0, 6, 3, 4, 8, 6, 3, 1, 4, 2, 8, 0, 3, 7, 6, 1, 7, 8, 7, 7, 4, 1, 1, 3, 3, 8, 7, 2, 6, 3, 8, 7, 0, 0, 0, 1, 1, 2, 8, 5, 1, 8, 1, 8, 2, 5, 0, 7, 3, 0, 3, 4, 0, 7, 1, 9, 1, 5, 3, 0}
var gr17 = [60]int{8, 9, 8, 5, 8, 8, 3, 9, 7, 2, 1, 7, 7, 6, 2, 9, 8, 5, 0, 7, 7, 8, 2, 6, 7, 5, 2, 5, 2, 9, 5, 1, 7, 5, 9, 8, 6, 8, 4, 4, 9, 5, 5, 6, 0, 4, 2, 9, 1, 9, 6, 4, 2, 4, 1, 3, 1, 9, 0, 5}
var gr18 = [60]int{0, 8, 0, 1, 0, 9, 1, 7, 5, 3, 6, 3, 5, 9, 1, 4, 7, 1, 8, 8, 1, 7, 6, 5, 2, 1, 2, 0, 2, 0, 1, 7, 4, 7, 8, 9, 5, 8, 9, 6, 9, 1, 6, 3, 6, 6, 7, 7, 2, 2, 0, 7, 7, 3, 5, 4, 1, 3, 4, 2}
var gr19 = [60]int{5, 3, 2, 2, 9, 6, 9, 4, 0, 2, 4, 4, 7, 6, 6, 7, 9, 9, 9, 3, 3, 4, 0, 1, 5, 0, 2, 3, 8, 7, 1, 1, 7, 9, 0, 0, 7, 0, 3, 0, 6, 7, 3, 3, 4, 0, 0, 8, 4, 9, 7, 5, 5, 1, 7, 4, 6, 3, 8, 8}
var gr20 = [60]int{9, 9, 7, 4, 7, 7, 3, 5, 2, 3, 9, 5, 2, 9, 4, 8, 2, 0, 5, 4, 9, 7, 9, 9, 1, 0, 6, 4, 1, 7, 9, 1, 3, 0, 1, 8, 1, 0, 4, 7, 1, 3, 8, 8, 9, 8, 6, 2, 7, 6, 2, 1, 3, 2, 5, 5, 8, 4, 2, 6}
var gr21 = [60]int{7, 1, 7, 6, 4, 7, 4, 8, 7, 8, 5, 3, 1, 8, 7, 1, 5, 1, 0, 6, 4, 3, 4, 5, 3, 8, 3, 1, 6, 5, 2, 3, 1, 4, 7, 7, 1, 5, 2, 8, 2, 3, 4, 5, 9, 6, 0, 9, 8, 2, 2, 5, 0, 0, 2, 2, 8, 8, 0, 0}
var gr22 = [60]int{2, 9, 8, 9, 6, 9, 8, 7, 8, 0, 6, 1, 2, 1, 6, 5, 2, 2, 3, 6, 8, 7, 9, 6, 4, 6, 1, 1, 3, 5, 9, 0, 9, 0, 0, 8, 7, 5, 2, 3, 5, 5, 7, 8, 5, 6, 3, 6, 0, 2, 4, 5, 4, 1, 8, 1, 9, 3, 2, 7}
var gr23 = [60]int{3, 6, 2, 2, 5, 2, 7, 5, 2, 7, 9, 9, 5, 2, 0, 0, 8, 4, 1, 8, 4, 2, 1, 9, 5, 3, 7, 7, 3, 1, 1, 4, 4, 9, 3, 3, 5, 6, 1, 8, 2, 6, 8, 9, 6, 0, 8, 1, 4, 4, 9, 7, 4, 9, 3, 5, 3, 5, 3, 2}
var gr24 = [60]int{0, 2, 2, 7, 0, 2, 2, 9, 2, 5, 2, 8, 6, 1, 8, 3, 7, 4, 7, 5, 4, 8, 9, 5, 3, 0, 3, 4, 8, 0, 9, 5, 7, 9, 1, 9, 2, 9, 6, 5, 6, 8, 0, 5, 0, 6, 5, 0, 3, 8, 3, 7, 5, 8, 8, 8, 8, 7, 2, 3}
var gr25 = [60]int{1, 5, 2, 9, 2, 2, 1, 2, 8, 5, 1, 5, 8, 1, 0, 0, 2, 4, 3, 3, 2, 6, 2, 7, 7, 1, 1, 4, 0, 4, 9, 5, 9, 3, 5, 9, 7, 9, 5, 5, 5, 2, 0, 8, 5, 0, 1, 5, 8, 0, 1, 1, 9, 3, 7, 9, 9, 9, 2, 9}
var gr26 = [60]int{2, 4, 1, 4, 1, 3, 0, 2, 5, 2, 2, 5, 1, 2, 4, 6, 0, 9, 2, 4, 0, 5, 9, 3, 6, 7, 2, 3, 6, 7, 0, 5, 9, 4, 8, 5, 8, 8, 8, 7, 9, 8, 1, 6, 0, 5, 6, 9, 5, 9, 5, 2, 4, 5, 2, 3, 0, 1, 6, 2}

var oldScores = []int{3, 6, 16, 18, 18, 18, 19, 21, 22, 25, 26, 28, 31, 35, 36, 37, 38, 40, 40, 41, 45, 48, 54, 55, 65, 81}
var oldRounds = []int{42, 43, 54, 56, 60, 63, 64, 70, 76, 79, 81, 85, 89, 91, 91, 93, 93, 94, 98, 99, 100, 100, 102, 106, 131, 167}
var oldSkips = []int{0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 5}
